#!/system/bin/sh
# Gov-Tuner Changelogs
# Copyright (C) 2016 Debuffer @ XDA-Developers
#	   With help from Paget96 and F4uzan
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox="/system/etc/GovTuner/busybox"
ver="2.4.2"
divider="==============================================="

$busybox echo "CHANGELOG FOR $ver"
$busybox echo "-------------------"
$busybox echo ""
$busybox echo "Govtuner command error fixed"
$busybox echo "Tune command error fixed"
$busybox echo "Added max_freq_hysteresis parameter to interactive governor"
$busybox echo "Added align_windows parameter to interactive governor"
$busybox echo "Fixed a bug where the frequency didn't go to the minimum possible when the screen is on"
$busybox echo "Rebalanced all the profiles target_loads"
$busybox echo "Rebalanced all the profiles above_hispeed delay"
$busybox echo ""
$busybox echo "$divider"
$busybox echo ""
$busybox echo "                     Update changelog commentary"
$busybox echo ""
$busybox echo "  This rebalancing improves the user experience being a bit more aggressive"
$busybox echo "                   to leave the minimum frequency."
$busybox echo "      This improvement gives the user more fludity and smoothness"
$busybox echo "        when switching between apps or using the device as usual."
$busybox echo "        This is under tests and feedbacks are really appreciated"
$busybox echo "mainly about the battery since the profiles were a bit improved to performance."
$busybox echo ""
$busybox echo $divider
$busybox echo ""
$busybox echo -n "b. Back to menu: "
read -r character
case $character in
b|B)$busybox clear;