#!/system/bin/sh
# Gov-Tuner Changelogs
# Copyright (C) 2016 - 2017 Debuffer and Senthil360 @ XDA-Developers
#	   With help from Paget96 and F4uzan
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
busybox="/system/etc/GovTuner/busybox"
changelog="/system/etc/GovTuner/changelog.txt"
ver="4.0.2"
$busybox echo "CHANGELOG FOR $ver"
$busybox echo "----------------------"
cat $changelog
$busybox echo ""
$busybox echo ""
$busybox echo -n "Press enter to go back"
read
clear
exit
