#!/system/bin/sh
# Gov-Tuner Changelogs
# Copyright (C) 2016 Debuffer and Senthil360 @ XDA-Developers
#	   With help from Paget96 and F4uzan
#=================================================================================================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=================================================================================================================================================#

busybox="/system/etc/GovTuner/busybox"
REG_DIR="/sys/devices/system/cpu/cpufreq"
CLU_DIR="/sys/devices/system/cpu/cpu0/cpufreq"
CUR_GOVERNOR=$($busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);
CLUSTER_DETECT="/sys/devices/system/cpu/cpu0/cpufreq/$CUR_GOVERNOR"
HON=/etc/GovTuner/zzmoove/HON
HOFF=/etc/GovTuner/zzmoove/HOFF

#For REGULAR and SMALL clusters
 if [ -d "/sys/devices/system/cpu/cpufreq/$CUR_GOVERNOR" ]; then
     FINAL_PATH=$REG_DIR
 elif [ -d "/sys/devices/system/cpu/cpu0/cpufreq/$CUR_GOVERNOR" ]; then
     FINAL_PATH=$CLU_DIR
 else
     echo "Unsupported device architecture"
 fi
 
 if [ -d "$CLUSTER_DETECT" ]; then
HOTPLUG=$($busybox cat /sys/devices/system/cpu/cpu0/cpufreq/zzmoove/disable_hotplug)
else
HOTPLUG=$($busybox cat /sys/devices/system/cpu/cpufreq/zzmoove/disable_hotplug)
fi

$busybox echo ""
$busybox echo ""
	$busybox echo -e "GovTuner has a Zzmoove hotplug tweaked configuration"
	$busybox echo "which is recommended while using Zzmoove governor."
	$busybox echo "Each profile has it's own configuration for hotplug."
	$busybox echo "This configuration will take more advantage controlling CPU ON/OFF"
	$busybox echo "and the scaling frequencies, combining all for the best user experience."
$busybox echo ""
$busybox echo ""
if [ $HOTPLUG == 1 ]; then
$busybox echo -e "Hotplug: Stock Hotplug"
$busybox echo ""
elif [ $HOTPLUG == 0 ]; then
$busybox echo -e "Hotplug: Zzmoove Tweaked Hotplug"
$busybox echo ""
fi
$busybox echo ""
	$busybox echo -e "Do you want to use Zzmoove's tweaked hotplug or stock hotplug?"
	$busybox echo -e " Z - Zzmoove"
	$busybox echo -e " S - Stock"
	$busybox echo ""
	$busybox echo -e "B - Back to menu"
$busybox echo ""
	$busybox echo -n "Select an option:"
	
read -r character
case $character in

z|Z)sh $HON;;

s|S)sh /$HOFF;;

b|B)$busybox clear;
sh /system/bin/govtuner;;
esac
