#!/system/bin/sh

busybox="/system/etc/GovTuner/busybox"

$busybox rm -rf /system/etc/init.d/Governor_Tuner
$busybox rm -rf /system/etc/init.d/GovTuner_balanced
$busybox rm -rf /system/etc/init.d/GovTuner_battery
$busybox rm -rf /system/etc/init.d/GovTuner_performance
$busybox rm -rf /system/bin/tune
$busybox rm -rf /system/bin/govtuner
rm -rf /system/etc/GovTuner 2>/dev/null
clear
exit
