#!/system/bin/sh
# Gov-Tuner Changelogs
# Copyright (C) 2016 Debuffer and Senthil360 @ XDA-Developers
#	   With help from Paget96 and F4uzan
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox="/system/etc/GovTuner/busybox"
CUR_GOVERNOR=$($busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);
REG_DIR="/sys/devices/system/cpu/cpufreq"
CLU_DIR="/sys/devices/system/cpu/cpu0/cpufreq"

 if [ -d "/sys/devices/system/cpu/cpufreq/$CUR_GOVERNOR" ]; then
     FINAL_PATH=$REG_DIR
 elif [ -d "/sys/devices/system/cpu/cpu0/cpufreq/$CUR_GOVERNOR" ]; then
     FINAL_PATH=$CLU_DIR
 else
     echo "Unsupported device architecture"
 fi

$busybox clear
$busybox echo "Turning Zzmoove hotplug ON."
stop mpdecision
$busybox echo "0" > "$FINAL_PATH/$CUR_GOVERNOR/disable_hotplug";
$busybox echo "0" > "$FINAL_PATH/$CUR_GOVERNOR/disable_hotplug_sleep";
$busybox echo ""
$busybox sleep 1
echo 0 > /etc/GovTuner/zzmoove/HCheck
$busybox echo "GovTuner's Zzmoove hotplug ON."
$busybox sleep 1
$busybox clear