#!/system/bin/sh
# Gov-Tuner Init Launcher
# Copyright (C) 2016 - 2017 Debuffer and Senthil360 @ XDA-Developers
#      With help from Paget96, F4uzan and GreekDragon
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

# You can edit this for your preference
SLEEP_TIME=60
busybox=/system/etc/GovTuner/busybox
$busybox rm /data/system/tuned 2>/dev/null
$busybox rm /data/system/tweaked 2>/dev/null
$busybox sleep $SLEEP_TIME
$busybox mount -o remount,rw /
$busybox echo "Init.d is Working" > /gt_test
$busybox mount -o remount,ro /
if [ -s /data/system/GovTuner/current/profile ]; then
   PROFILE=$($busybox cat /data/system/GovTuner/current/profile);
   $busybox mount -o remount,rw /data
   $busybox echo 1 > /data/system/first_launch
   $busybox date >> /data/system/first_launch
   $busybox sh /data/system/GovTuner/current/$PROFILE &
   $busybox mount -o remount,ro /data
fi
