#!/system/bin/sh
ver="2.0.4.3"
# Copyright (C) 2016 Debuffer @ xda-developers
# Thanks to @Paget96 @F4uzan
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

# Upgrade tool, this removes Governor_profiles in case it exists
# We need to remove it since it directly conflicts with the new version (since the name differs)

id="$(id)"; id="${id#*=}"; id="${id%%\(*}"; id="${id%% *}"
busybox sleep 1
busybox clear
busybox sleep 1
busybox echo "You are running version $ver"
busybox sleep 1
busybox echo "Checking root"; busybox sleep 0.3; busybox clear;
busybox echo "Checking root."; busybox sleep 0.3; busybox clear;
busybox echo "Checking root.."; busybox sleep 0.3; busybox clear;
busybox echo "Checking root..."; busybox sleep 0.3; busybox clear;
busybox echo "Checking root"; busybox sleep 0.3; busybox clear;
busybox echo "Checking root."; busybox sleep 0.3; busybox clear;
busybox echo "Checking root.."; busybox sleep 0.3; 
busybox clear; busybox echo "Checking root..."; 

if [ "$id" != "0" ] && [ "$id" != "root" ]; then
	busybox sleep 1
	busybox echo ""
	busybox echo ""
	busybox echo "    You don't have ROOT or there is an issue with it..."
	busybox echo "    Please type su first (terminal emulator)"
	busybox echo "    Then type tune"
	busybox echo "    Enable run as ROOT (script manager)"
	busybox echo ""
	busybox sleep 1
	exit
	else
		busybox clear
		busybox sleep 0.5
		busybox echo "Root sucessfully acquired."
		busybox sleep 1
		busybox echo ""
		busybox echo "Executing script"
fi

if [ -f /system/etc/init.d/Governor_profiles ]; then
	busybox mount -o remount, rw /system
	busybox rm -rf /system/etc/init.d/Governor_profiles
	busybox mount -o remount, ro /system
fi

# Minimum CPU frequency
MIN_CPU_FREQ=$(busybox cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq);

# Maximum CPU frequency
MAX_CPU_FREQ=$(busybox cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq);

# Currently used governor
CUR_GOVERNOR=$(busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);

# Detects whether user uses a dual-cluster CPU (SD810, SD820, etc) or not
CLUSTER_DETECT="/sys/devices/system/cpu/cpu0/cpufreq/$CUR_GOVERNOR"

# Dual cluster, selects only first two or four cores
CPUFREQ_CLUSTER="/sys/devices/system/cpu/cpu0/cpufreq"

# Regular CPUFreq directory
CPUFREQ_REGULAR="/sys/devices/system/cpu/cpufreq"

if [ -d "$CLUSTER_DETECT" ]; then
	CLUSTER=$CPUFREQ_CLUSTER
 	else
	CLUSTER=$CPUFREQ_REGULAR
fi

# Set the finalized governor path
GOVERNOR=$CLUSTER/$CUR_GOVERNOR

# GOVERNOR TWEAKS #

# INTERACTIVE

if [ "$CUR_GOVERNOR" = "interactive" ]; then
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		busybox echo "30000" > "$GOVERNOR/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		busybox echo "0" > "$GOVERNOR/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		busybox echo "0" > "$GOVERNOR/boostpulse";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then	
		busybox echo "0" > "$GOVERNOR/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		busybox echo "90" > "$GOVERNOR/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		busybox echo "1200000" > "$GOVERNOR/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		busybox echo "0" > "$GOVERNOR/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		busybox echo "80000" > "$GOVERNOR/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		busybox echo "90" > "$GOVERNOR/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		busybox echo "30000" > "$GOVERNOR/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		busybox echo "120000" > "$GOVERNOR/timer_slack";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		busybox echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	fi
	busybox echo "$CUR_GOVERNOR tweaks applied."
	exit
fi

# CONSERVATIVE

if [ $CUR_GOVERNOR = "conservative" ]; then
	busybox echo "95" > "$GOVERNOR/down_threshold";
	busybox echo "1" > "$GOVERNOR/freq_step";
	busybox echo "1" > "$GOVERNOR/ignore_nice_load";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "99" > "$GOVERNOR/up_threshold";
	busybox echo "Conservative tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# YANKACTIVE

if [ $CUR_GOVERNOR = "yankactive" ]; then
		if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		busybox echo "30000" > "$GOVERNOR/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		busybox echo "0" > "$GOVERNOR/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		busybox echo "0" > "$GOVERNOR/boostpulse";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then	
		busybox echo "0" > "$GOVERNOR/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		busybox echo "90" > "$GOVERNOR/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		busybox echo "1200000" > "$GOVERNOR/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		busybox echo "0" > "$GOVERNOR/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		busybox echo "80000" > "$GOVERNOR/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		busybox echo "90" > "$GOVERNOR/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		busybox echo "30000" > "$GOVERNOR/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		busybox echo "120000" > "$GOVERNOR/timer_slack";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		busybox echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	fi
	busybox echo "Yankactive tweaks applied."
	exit
fi


# INTELLIACTIVE

if [ $CUR_GOVERNOR = "intelliactive" ]; then
	busybox echo "30000" > "$GOVERNOR/above_hispeed_delay";
	busybox echo "0" > "$GOVERNOR/boost";
	busybox echo "0" > "$GOVERNOR/boostpulse";
	busybox echo "0" > "$GOVERNOR/boostpulse_duration";
	busybox echo "90" > "$GOVERNOR/go_hispeed_load";
	busybox echo "1200000" > "$GOVERNOR/hispeed_freq";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "80000" > "$GOVERNOR/min_sample_time";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "1100000" > "$GOVERNOR/sync_freq";
	busybox echo "90" > "$GOVERNOR/target_loads";
	busybox echo "30000" > "$GOVERNOR/timer_rate";
	busybox echo "120000" > "$GOVERNOR/timer_slack";
	busybox echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	busybox echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	busybox echo "Intelliactive tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# BIOSHOCK 

if [ $CUR_GOVERNOR = "bioshock" ]; then
	busybox echo "95" > "$GOVERNOR/down_threshold";
	busybox echo "1" > "$GOVERNOR/freq_step";
	busybox echo "1" > "$GOVERNOR/ignore_nice_load";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "99" > "$GOVERNOR/up_threshold";
	busybox echo "Bioshock tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# LIONFISH 

if [ $CUR_GOVERNOR = "lionfish" ]; then
	busybox echo "95" > "$GOVERNOR/down_threshold";
	busybox echo "1" > "$GOVERNOR/freq_step";
	busybox echo "1" > "$GOVERNOR/ignore_nice_load";
	busybox echo "1000000" > "$GOVERNOR/jump_level";
	busybox echo "99" > "$GOVERNOR/jump_threshold";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "99" > "$GOVERNOR/up_threshold";
	busybox echo "Lionfish tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# IMPULSE 

if [ $CUR_GOVERNOR = "impulse" ]; then
	busybox echo "30000" > "$GOVERNOR/above_hispeed_delay";
	busybox echo "90" > "$GOVERNOR/go_hispeed_load";
	busybox echo "1200000" > "$GOVERNOR/hispeed_freq";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "80000" > "$GOVERNOR/min_sample_time";
	busybox echo "30000" > "$GOVERNOR/timer_rate";
	busybox echo "120000" > "$GOVERNOR/timer_slack";
	busybox echo "90" > "$GOVERNOR/target_loads";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/max_freq_hysteresis";
	busybox echo "0" > "$GOVERNOR/align_windows";
	busybox echo "0" > "$GOVERNOR/powersave_bias";
	busybox echo "Impulse tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# UBERDEMAND 

if [ $CUR_GOVERNOR = "uberdemand" ]; then
	busybox echo "20" > "$GOVERNOR/down_differential";
	busybox echo "0" > "$GOVERNOR/ignore_nice_load";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "0" > "$GOVERNOR/powersave_bias";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/second_phase_freq";
	busybox echo "95" > "$GOVERNOR/up_threshold";
	busybox echo "Uberdemand tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# ELECTROACTIVE 

if [ $CUR_GOVERNOR = "electroactive" ]; then
	busybox echo "0" > "$GOVERNOR/boostfreq";
	busybox echo "0" > "$GOVERNOR/boostpulse";
	busybox echo "15" > "$GOVERNOR/down_differential";
	busybox echo "1200000" > "$GOVERNOR/freq_responsiveness";
	busybox echo "30" > "$GOVERNOR/freq_step";
	busybox echo "0" > "$GOVERNOR/ignore_nice_load";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "90" > "$GOVERNOR/micro_freq_up_threshold";
	busybox echo "0" > "$GOVERNOR/powersave_bias";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "90" > "$GOVERNOR/up_threshold";
	busybox echo "600000" > "$GOVERNOR/up_threshold_min_freq";
	busybox echo "Electroactive tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# INTELLIMM

if [ $CUR_GOVERNOR = "intelimm" ]; then
	busybox echo "15" > "$GOVERNOR/down_differential";
	busybox echo "15" > "$GOVERNOR/down_differential_multi_core";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/freq_down_step";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/freq_down_step_barrier";
	busybox echo "0" > "$GOVERNOR/ignore_nice_load";
	busybox echo "$MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ" > "$GOVERNOR/input_event_min_freq";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/optimal_freq";
	busybox echo "0" > "$GOVERNOR/powersave_bias";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "80000" > "$GOVERNOR/sampling_rate";
	busybox echo "80000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "0" > "$GOVERNOR/shortcut";
	busybox echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	busybox echo "95" > "$GOVERNOR/up_threshold";
	busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	busybox echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	busybox echo "0" > "$GOVERNOR/up_threshold_multi_core";
	busybox echo "InteliMM tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# BARRY_ALLEN

if [ $CUR_GOVERNOR = "barry_allen" ]; then
	busybox echo "30000" > "$GOVERNOR/above_hispeed_delay";
	busybox echo "0" > "$GOVERNOR/ba_lock";
	busybox echo "0" > "$GOVERNOR/boost";
	busybox echo "0" > "$GOVERNOR/boostpulse";
	busybox echo "0" > "$GOVERNOR/boostpulse_duration";
	busybox echo "90" > "$GOVERNOR/go_hispeed_load";
	busybox echo "1200000" > "$GOVERNOR/hispeed_freq";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "80000" > "$GOVERNOR/min_sample_time";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "1100000" > "$GOVERNOR/sync_freq";
	busybox echo "90" > "$GOVERNOR/target_loads";
	busybox echo "30000" > "$GOVERNOR/timer_rate";
	busybox echo "120000" > "$GOVERNOR/timer_slack";
	busybox echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	busybox echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	busybox echo "Barry_allen tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# BLUACTIVE

if [ $CUR_GOVERNOR = "bluactive" ]; then
	busybox echo "30000" > "$GOVERNOR/above_hispeed_delay";
	busybox echo "0" > "$GOVERNOR/boost";
	busybox echo "0" > "$GOVERNOR/boostpulse";
	busybox echo "0" > "$GOVERNOR/boostpulse_duration";
	busybox echo "90" > "$GOVERNOR/go_hispeed_load";
	busybox echo "1200000" > "$GOVERNOR/hispeed_freq";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "80000" > "$GOVERNOR/min_sample_time";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "1100000" > "$GOVERNOR/sync_freq";
	busybox echo "90" > "$GOVERNOR/target_loads";
	busybox echo "30000" > "$GOVERNOR/timer_rate";
	busybox echo "120000" > "$GOVERNOR/timer_slack";
	busybox echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	busybox echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	busybox echo "Bluactive tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# DANCEDANCE

if [ $CUR_GOVERNOR = "dancedance" ]; then
	busybox echo "95" > "$GOVERNOR/down_threshold";
	busybox echo "1" > "$GOVERNOR/freq_step";
	busybox echo "1" > "$GOVERNOR/ignore_nice_load";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "99" > "$GOVERNOR/up_threshold";
	busybox echo "Dancedance tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# LIONHEART 

if [ $CUR_GOVERNOR = "lionheart" ]; then
	busybox echo "95" > "$GOVERNOR/down_threshold";
	busybox echo "1" > "$GOVERNOR/freq_step";
	busybox echo "1" > "$GOVERNOR/ignore_nice_load";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "99" > "$GOVERNOR/up_threshold";
	busybox echo "Lionheart tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# PEGASUSQ

if [ $CUR_GOVERNOR = "pegasusq" ]; then
	busybox echo "15" > "$GOVERNOR/down_differential";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/freq_responsiveness";
	busybox echo "30" > "$GOVERNOR/freq_step";
	busybox echo "0" > "$GOVERNOR/ignore_nice_load";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "95" > "$GOVERNOR/up_threshold";
	busybox echo "600000" > "$GOVERNOR/up_threshold_min_freq";
	busybox echo "PegasusQ tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# ONDEMAND

if [ $CUR_GOVERNOR = "ondemand" ]; then
	busybox echo "15" > "$GOVERNOR/down_differential";
	busybox echo "0" > "$GOVERNOR/ignore_nice_load";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/optimal_freq";
	busybox echo "0" > "$GOVERNOR/powersave_bias";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "20000" > "$GOVERNOR/sampling_rate";
	busybox echo "20000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "1100000" > "$GOVERNOR/sync_freq";
	busybox echo "95" > "$GOVERNOR/up_threshold";
	busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	busybox echo "0" > "$GOVERNOR/up_threshold_multi_core";
	busybox echo "Ondemand tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# SMARTMAX 

if [ $CUR_GOVERNOR = "smartmax" ]; then
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/awake_ideal_freq";
	busybox echo "0" > "$GOVERNOR/boost_duration";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/boost_freq";
	busybox echo "32" > "$GOVERNOR/debug_mask";
	busybox echo "10000" > "$GOVERNOR/down_rate";
	busybox echo "0" > "$GOVERNOR/ignore_nice";
	busybox echo "0" > "$GOVERNOR/input_boost_duration";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "100" > "$GOVERNOR/max_cpu_load";
	busybox echo "5" > "$GOVERNOR/min_cpu_load";
	busybox echo "20000" > "$GOVERNOR/min_sampling_rate";
	busybox echo "162000" > "$GOVERNOR/ramp_down_step";
	busybox echo "0" > "$GOVERNOR/ramp_up_during_boost";
	busybox echo "100000" > "$GOVERNOR/ramp_up_step";
	busybox echo "20000" > "$GOVERNOR/sampling_rate";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/suspend_ideal_freq";
	busybox echo "0" > "$GOVERNOR/touch_poke_freq";
	busybox echo "0" > "$GOVERNOR/up_rate";
	busybox echo "Smartmax tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# OPTIMAX

if [ $CUR_GOVERNOR = "optimax" ]; then
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/optimal_freq";
	busybox echo "0" > "$GOVERNOR/optimal_max_freq";
	busybox echo "0" > "$GOVERNOR/powersave_bias";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "20000" > "$GOVERNOR/sampling_rate";
	busybox echo "20000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "1100000" > "$GOVERNOR/sync_freq";
	busybox echo "95" > "$GOVERNOR/up_threshold";
	busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	busybox echo "0" > "$GOVERNOR/up_threshold_multi_core";
	busybox echo "Optimax tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# CONSERVATIVEX

if [ $CUR_GOVERNOR = "conservativex" ]; then
	busybox echo "95" > "$GOVERNOR/down_threshold";
	busybox echo "1" > "$GOVERNOR/freq_step";
	busybox echo "1" > "$GOVERNOR/ignore_nice_load";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "50000" > "$GOVERNOR/sampling_rate";
	busybox echo "10000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "99" > "$GOVERNOR/up_threshold";
	busybox echo "ConservativeX tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# INTERACTIVE_PRO

if [ $CUR_GOVERNOR = "interactive_pro" ]; then
	busybox echo "30000" > "$GOVERNOR/above_hispeed_delay";
	busybox echo "0" > "$GOVERNOR/boost";
	busybox echo "0" > "$GOVERNOR/boostpulse_duration";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/freq_calc_thresh";
	busybox echo "90" > "$GOVERNOR/go_hispeed_load";
	busybox echo "1200000" > "$GOVERNOR/hispeed_freq";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "80000" > "$GOVERNOR/min_sample_time";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "1100000" > "$GOVERNOR/sync_freq";
	busybox echo "90" > "$GOVERNOR/target_loads";
	busybox echo "30000" > "$GOVERNOR/timer_rate";
	busybox echo "120000" > "$GOVERNOR/timer_slack";
	busybox echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	busybox echo "Interactive_pro tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# WHEATLEY

if [ $CUR_GOVERNOR = "wheatley" ]; then
	busybox echo "5" > "$GOVERNOR/allowed_misses";
	busybox echo "0" > "$GOVERNOR/ignore_nice_load";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "0" > "$GOVERNOR/powersave_bias";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "20000" > "$GOVERNOR/sampling_rate";
	busybox echo "20000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "10000" > "$GOVERNOR/target_residency";
	busybox echo "95" > "$GOVERNOR/up_threshold";
	busybox echo "Wheatley tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# ONDEMAND PLUS

if [ $CUR_GOVERNOR = "ondemandplus" ]; then
	busybox echo "20" > "$GOVERNOR/down_differential";
	busybox echo "1500000" > "$GOVERNOR/inter_hifreq";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/inter_lofreq";
	busybox echo "2" > "$GOVERNOR/inter_staycycles";
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/staycycles_resetfreq";
	busybox echo "30000" > "$GOVERNOR/timer_rate";
	busybox echo "95" > "$GOVERNOR/up_threshold";
	busybox echo "OndemandPlus tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# SMARTMAX EPS

if [ $CUR_GOVERNOR = "smartmax_eps" ]; then
	busybox echo "0" > "$GOVERNOR/io_is_busy";
	busybox echo "100" > "$GOVERNOR/max_cpu_load";
	busybox echo "20" > "$GOVERNOR/min_cpu_load";
	busybox echo "20000" > "$GOVERNOR/min_sampling_rate";
	busybox echo "700000" > "$GOVERNOR/ramp_down_step";
	busybox echo "0" > "$GOVERNOR/ramp_up_during_boost";
	busybox echo "0" > "$GOVERNOR/ramp_up_step";
	busybox echo "600000" > "$GOVERNOR/awake_ideal_freq";
	busybox echo "0" > "$GOVERNOR/boost_duration";
	busybox echo "0" > "$GOVERNOR/boost_freq";
	busybox echo "0" > "$GOVERNOR/debug_mask";
	busybox echo "30000" > "$GOVERNOR/down_rate";
	busybox echo "0" > "$GOVERNOR/ignore_nice";
	busybox echo "0" > "$GOVERNOR/input_boost_duration";
	busybox echo "Smartmax_eps tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# INTELLIDEMAND

if [ $CUR_GOVERNOR = "intellidemand" ]; then
	busybox echo "$MIN_CPU_FREQ" > "$GOVERNOR/optimal_freq";
	busybox echo "0" > "$GOVERNOR/powersave_bias";
	busybox echo "1" > "$GOVERNOR/sampling_down_factor";
	busybox echo "2" > "$GOVERNOR/sampling_easy_factor";
	busybox echo "3" > "$GOVERNOR/sampling_interim_factor";
	busybox echo "20000" > "$GOVERNOR/sampling_rate";
	busybox echo "20000" > "$GOVERNOR/sampling_rate_min";
	busybox echo "1100000" > "$GOVERNOR/sync_freq";
	busybox echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	busybox echo "40000" > "$GOVERNOR/ui_sampling_rate";
	busybox echo "40" > "$GOVERNOR/ui_timeout";
	busybox echo "95" > "$GOVERNOR/up_threshold";
	busybox echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	busybox echo "0" > "$GOVERNOR/up_threshold_multi_core";
	busybox echo "Intellidemand tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# TRIPNDROID

if [ $CUR_GOVERNOR = "tripndroid" ]; then
	busybox echo "10000" > "$GOVERNOR/down_sample_time";
	busybox echo "90" > "$GOVERNOR/go_hispeed_load";
	busybox echo "1200000" > "$GOVERNOR/hispeed_freq";
	busybox echo "30000" > "$GOVERNOR/timer_rate";
	busybox echo "50000" > "$GOVERNOR/up_sample_time";
	busybox echo "Tripndroid tweaks applied."
	busybox echo "Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi

# No compatible governor is detected
# Put other governor above this, don't let this be sandwiched by other governor
busybox echo "$CUR_GOVERNOR governor is not supported yet."
busybox echo  "You can request the support for this governor in the official XDA thread."
