#!/system/bin/sh
# Gov-Tuner 2.0.4
# Copyright (C) 2016 Debuffer @ XDA-Developers
# With help from Paget96 and F4uzan from XDA-Developers
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

# Upgrade tool, this removes Governor_profiles in case it exists
# We need to remove it since it directly conflicts with the new version (since the name differs)
if [ -f /system/etc/init.d/Governor_profiles ]; then
	mount -o remount, rw /system
	rm /system/etc/init.d/Governor_profiles
	mount -o remount, ro /system
fi

# Minimum CPU frequency
MIN_CPU_FREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq);

# Maximum CPU frequency
MAX_CPU_FREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq);

# Currently used governor
CUR_GOVERNOR=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);

# Detects whether user uses a dual-cluster CPU (SD810, SD820, etc) or not
CLUSTER_DETECT="/sys/devices/system/cpu/cpu0/cpufreq/$CUR_GOVERNOR"
CLUSTER2_DETECT="/sys/devices/system/cpu/cpu4/cpufreq/$CUR_GOVERNOR"
CLUSTER3_DETECT="/sys/devices/system/cpu/cpu5/cpufreq/$CUR_GOVERNOR"
CLUSTER4_DETECT="/sys/devices/system/cpu/cpu6/cpufreq/$CUR_GOVERNOR"
CLUSTER5_DETECT="/sys/devices/system/cpu/cpu7/cpufreq/$CUR_GOVERNOR"

# Dual cluster, selects only first two or four cores
CPUFREQ_CLUSTER="/sys/devices/system/cpu/cpu0/cpufreq"
CPUFREQ_CLUSTER2="/sys/devices/system/cpu/cpu4/cpufreq"
CPUFREQ_CLUSTER3="/sys/devices/system/cpu/cpu5/cpufreq"
CPUFREQ_CLUSTER4="/sys/devices/system/cpu/cpu6/cpufreq"
CPUFREQ_CLUSTER5="/sys/devices/system/cpu/cpu7/cpufreq"

# Regular CPUFreq directory
CPUFREQ_REGULAR="/sys/devices/system/cpu/cpufreq"

if [ -d "$CLUSTER_DETECT" ]; then
	CLUSTER=$CPUFREQ_CLUSTER
	else
	CLUSTER=$CPUFREQ_REGULAR
fi

if [ -d "$CLUSTER2_DETECT" ]; then
	CLUSTER2=$CPUFREQ_CLUSTER2
	else
	CLUSTER2=$CPUFREQ_REGULAR
fi

if [ -d "$CLUSTER3_DETECT" ]; then
	CLUSTER3=$CPUFREQ_CLUSTER3
	else
	CLUSTER3=$CPUFREQ_REGULAR
fi

if [ -d "$CLUSTER4_DETECT" ]; then
	CLUSTER4=$CPUFREQ_CLUSTER4
	else
	CLUSTER4=$CPUFREQ_REGULAR
fi

if [ -d "$CLUSTER5_DETECT" ]; then
	CLUSTER5=$CPUFREQ_CLUSTER5
	else
	CLUSTER5=$CPUFREQ_REGULAR
fi

# Set the finalized governor path
GOVERNOR=$CLUSTER/$CLUSTER2/$CLUSTER3/$CLUSTER4/$CLUSTER5/$CUR_GOVERNOR

# GOVERNOR TWEAKS #

# INTERACTIVE

if [ $CUR_GOVERNOR = "interactive" ];
	echo "30000" > "$GOVERNOR/above_hispeed_delay";
	echo "0" > "$GOVERNOR/boost";
	echo "0" > "$GOVERNOR/boostpulse";
	echo "0" > "$GOVERNOR/boostpulse_duration";
	echo "90" > "$GOVERNOR/go_hispeed_load";
	echo "1200000" > "$GOVERNOR/hispeed_freq";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "80000" > "$GOVERNOR/min_sample_time";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "90" > "$GOVERNOR/target_loads";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "120000" > "$GOVERNOR/timer_slack";
	echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "Interactive tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# CONSERVATIVE

if [ $CUR_GOVERNOR = "conservative" ]; then
	echo "95" > "$GOVERNOR/down_threshold";
	echo "1" > "$GOVERNOR/freq_step";
	echo "1" > "$GOVERNOR/ignore_nice_load";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "99" > "$GOVERNOR/up_threshold";
	echo "Conservative tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# YANKACTIVE

if [ $CUR_GOVERNOR = "yankactive" ]; then
	echo "30000" > "$GOVERNOR/above_hispeed_delay";
	echo "0" > "$GOVERNOR/boost";
	echo "0" > "$GOVERNOR/boostpulse";
	echo "0" > "$GOVERNOR/boostpulse_duration";
	echo "90" > "$GOVERNOR/go_hispeed_load";
	echo "1200000" > "$GOVERNOR/hispeed_freq";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "80000" > "$GOVERNOR/min_sample_time";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "90" > "$GOVERNOR/target_loads";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "120000" > "$GOVERNOR/timer_slack";
	echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "Yankactive tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi


# INTELLIACTIVE

if [ $CUR_GOVERNOR = "intelliactive" ]; then
	echo "30000" > "$GOVERNOR/above_hispeed_delay";
	echo "0" > "$GOVERNOR/boost";
	echo "0" > "$GOVERNOR/boostpulse";
	echo "0" > "$GOVERNOR/boostpulse_duration";
	echo "90" > "$GOVERNOR/go_hispeed_load";
	echo "1200000" > "$GOVERNOR/hispeed_freq";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "80000" > "$GOVERNOR/min_sample_time";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "1100000" > "$GOVERNOR/sync_freq";
	echo "90" > "$GOVERNOR/target_loads";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "120000" > "$GOVERNOR/timer_slack";
	echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "Intelliactive tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# BIOSHOCK 

if [ $CUR_GOVERNOR = "bioshock" ]; then
	echo "95" > "$GOVERNOR/down_threshold";
	echo "1" > "$GOVERNOR/freq_step";
	echo "1" > "$GOVERNOR/ignore_nice_load";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "99" > "$GOVERNOR/up_threshold";
	echo "Bioshock tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# LIONFISH 

if [ $CUR_GOVERNOR = "lionfish" ]; then
	echo "95" > "$GOVERNOR/down_threshold";
	echo "1" > "$GOVERNOR/freq_step";
	echo "1" > "$GOVERNOR/ignore_nice_load";
	echo "1000000" > "$GOVERNOR/jump_level";
	echo "99" > "$GOVERNOR/jump_threshold";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "99" > "$GOVERNOR/up_threshold";
	echo "Lionfish tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# IMPULSE 

if [ $CUR_GOVERNOR = "impulse" ]; then
	echo "30000" > "$GOVERNOR/above_hispeed_delay";
	echo "90" > "$GOVERNOR/go_hispeed_load";
	echo "1200000" > "$GOVERNOR/hispeed_freq";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "80000" > "$GOVERNOR/min_sample_time";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "120000" > "$GOVERNOR/timer_slack";
	echo "90" > "$GOVERNOR/target_loads";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/max_freq_hysteresis";
	echo "0" > "$GOVERNOR/align_windows";
	echo "0" > "$GOVERNOR/powersave_bias";
	echo "Impulse tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# UBERDEMAND 

if [ $CUR_GOVERNOR = "uberdemand" ]; then
	echo "20" > "$GOVERNOR/down_differential";
	echo "0" > "$GOVERNOR/ignore_nice_load";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "0" > "$GOVERNOR/powersave_bias";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/second_phase_freq";
	echo "95" > "$GOVERNOR/up_threshold";
	echo "Uberdemand tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# ELECTROACTIVE 

if [ $CUR_GOVERNOR = "electroactive" ]; then
	echo "0" > "$GOVERNOR/boostfreq";
	echo "0" > "$GOVERNOR/boostpulse";
	echo "15" > "$GOVERNOR/down_differential";
	echo "1200000" > "$GOVERNOR/freq_responsiveness";
	echo "30" > "$GOVERNOR/freq_step";
	echo "0" > "$GOVERNOR/ignore_nice_load";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "90" > "$GOVERNOR/micro_freq_up_threshold";
	echo "0" > "$GOVERNOR/powersave_bias";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "90" > "$GOVERNOR/up_threshold";
	echo "600000" > "$GOVERNOR/up_threshold_min_freq";
	echo "Electroactive tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# INTELLIMM

if [ $CUR_GOVERNOR = "intelimm" ]; then
	echo "15" > "$GOVERNOR/down_differential";
	echo "15" > "$GOVERNOR/down_differential_multi_core";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/freq_down_step";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/freq_down_step_barrier";
	echo "0" > "$GOVERNOR/ignore_nice_load";
	echo "$MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ" > "$GOVERNOR/input_event_min_freq";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/optimal_freq";
	echo "0" > "$GOVERNOR/powersave_bias";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "80000" > "$GOVERNOR/sampling_rate";
	echo "80000" > "$GOVERNOR/sampling_rate_min";
	echo "0" > "$GOVERNOR/shortcut";
	echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	echo "95" > "$GOVERNOR/up_threshold";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	echo "0" > "$GOVERNOR/up_threshold_multi_core";
	echo "InteliMM tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# BARRY_ALLEN

if [ $CUR_GOVERNOR = "barry_allen" ]; then
	echo "30000" > "$GOVERNOR/above_hispeed_delay";
	echo "0" > "$GOVERNOR/ba_lock";
	echo "0" > "$GOVERNOR/boost";
	echo "0" > "$GOVERNOR/boostpulse";
	echo "0" > "$GOVERNOR/boostpulse_duration";
	echo "90" > "$GOVERNOR/go_hispeed_load";
	echo "1200000" > "$GOVERNOR/hispeed_freq";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "80000" > "$GOVERNOR/min_sample_time";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "1100000" > "$GOVERNOR/sync_freq";
	echo "90" > "$GOVERNOR/target_loads";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "120000" > "$GOVERNOR/timer_slack";
	echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "Barry_allen tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# BLUACTIVE

if [ $CUR_GOVERNOR = "bluactive" ]; then
	echo "30000" > "$GOVERNOR/above_hispeed_delay";
	echo "0" > "$GOVERNOR/boost";
	echo "0" > "$GOVERNOR/boostpulse";
	echo "0" > "$GOVERNOR/boostpulse_duration";
	echo "90" > "$GOVERNOR/go_hispeed_load";
	echo "1200000" > "$GOVERNOR/hispeed_freq";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "80000" > "$GOVERNOR/min_sample_time";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "1100000" > "$GOVERNOR/sync_freq";
	echo "90" > "$GOVERNOR/target_loads";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "120000" > "$GOVERNOR/timer_slack";
	echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "Bluactive tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# DANCEDANCE

if [ $CUR_GOVERNOR = "dancedance" ]; then
	echo "95" > "$GOVERNOR/down_threshold";
	echo "1" > "$GOVERNOR/freq_step";
	echo "1" > "$GOVERNOR/ignore_nice_load";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "99" > "$GOVERNOR/up_threshold";
	echo "Dancedance tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# LIONHEART 

if [ $CUR_GOVERNOR = "lionheart" ]; then
	echo "95" > "$GOVERNOR/down_threshold";
	echo "1" > "$GOVERNOR/freq_step";
	echo "1" > "$GOVERNOR/ignore_nice_load";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "99" > "$GOVERNOR/up_threshold";
	echo "Lionheart tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# PEGASUSQ

if [ $CUR_GOVERNOR = "pegasusq" ]; then
	echo "15" > "$GOVERNOR/down_differential";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/freq_responsiveness";
	echo "30" > "$GOVERNOR/freq_step";
	echo "0" > "$GOVERNOR/ignore_nice_load";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "95" > "$GOVERNOR/up_threshold";
	echo "600000" > "$GOVERNOR/up_threshold_min_freq";
	echo "PegasusQ tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# ONDEMAND

if [ $CUR_GOVERNOR = "ondemand" ]; then
	echo "15" > "$GOVERNOR/down_differential";
	echo "0" > "$GOVERNOR/ignore_nice_load";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/optimal_freq";
	echo "0" > "$GOVERNOR/powersave_bias";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "20000" > "$GOVERNOR/sampling_rate";
	echo "20000" > "$GOVERNOR/sampling_rate_min";
	echo "1100000" > "$GOVERNOR/sync_freq";
	echo "95" > "$GOVERNOR/up_threshold";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "0" > "$GOVERNOR/up_threshold_multi_core";
	echo "Ondemand tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# SMARTMAX 

if [ $CUR_GOVERNOR = "smartmax" ]; then
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/awake_ideal_freq";
	echo "0" > "$GOVERNOR/boost_duration";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/boost_freq";
	echo "32" > "$GOVERNOR/debug_mask";
	echo "10000" > "$GOVERNOR/down_rate";
	echo "0" > "$GOVERNOR/ignore_nice";
	echo "0" > "$GOVERNOR/input_boost_duration";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "100" > "$GOVERNOR/max_cpu_load";
	echo "5" > "$GOVERNOR/min_cpu_load";
	echo "20000" > "$GOVERNOR/min_sampling_rate";
	echo "162000" > "$GOVERNOR/ramp_down_step";
	echo "0" > "$GOVERNOR/ramp_up_during_boost";
	echo "100000" > "$GOVERNOR/ramp_up_step";
	echo "20000" > "$GOVERNOR/sampling_rate";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/suspend_ideal_freq";
	echo "0" > "$GOVERNOR/touch_poke_freq";
	echo "0" > "$GOVERNOR/up_rate";
	echo "Smartmax tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# OPTIMAX

if [ $CUR_GOVERNOR = "optimax" ]; then
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/optimal_freq";
	echo "0" > "$GOVERNOR/optimal_max_freq";
	echo "0" > "$GOVERNOR/powersave_bias";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "20000" > "$GOVERNOR/sampling_rate";
	echo "20000" > "$GOVERNOR/sampling_rate_min";
	echo "1100000" > "$GOVERNOR/sync_freq";
	echo "95" > "$GOVERNOR/up_threshold";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "0" > "$GOVERNOR/up_threshold_multi_core";
	echo "Optimax tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# CONSERVATIVEX

if [ $CUR_GOVERNOR = "conservativex" ]; then
	echo "95" > "$GOVERNOR/down_threshold";
	echo "1" > "$GOVERNOR/freq_step";
	echo "1" > "$GOVERNOR/ignore_nice_load";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "50000" > "$GOVERNOR/sampling_rate";
	echo "10000" > "$GOVERNOR/sampling_rate_min";
	echo "99" > "$GOVERNOR/up_threshold";
	echo "ConservativeX tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# INTERACTIVE_PRO

if [ $CUR_GOVERNOR = "interactive_pro" ]; then
	echo "30000" > "$GOVERNOR/above_hispeed_delay";
	echo "0" > "$GOVERNOR/boost";
	echo "0" > "$GOVERNOR/boostpulse_duration";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/freq_calc_thresh";
	echo "90" > "$GOVERNOR/go_hispeed_load";
	echo "1200000" > "$GOVERNOR/hispeed_freq";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "80000" > "$GOVERNOR/min_sample_time";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "1100000" > "$GOVERNOR/sync_freq";
	echo "90" > "$GOVERNOR/target_loads";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "120000" > "$GOVERNOR/timer_slack";
	echo "1200000" > "$GOVERNOR/up_threshold_any_cpu_freq";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "Interactive_pro tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# WHEATLEY

if [ $CUR_GOVERNOR = "wheatley" ]; then
	echo "5" > "$GOVERNOR/allowed_misses";
	echo "0" > "$GOVERNOR/ignore_nice_load";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "0" > "$GOVERNOR/powersave_bias";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "20000" > "$GOVERNOR/sampling_rate";
	echo "20000" > "$GOVERNOR/sampling_rate_min";
	echo "10000" > "$GOVERNOR/target_residency";
	echo "95" > "$GOVERNOR/up_threshold";
	echo "Wheatley tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# ONDEMAND PLUS

if [ $CUR_GOVERNOR = "ondemandplus" ]; then
	echo "20" > "$GOVERNOR/down_differential";
	echo "1500000" > "$GOVERNOR/inter_hifreq";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/inter_lofreq";
	echo "2" > "$GOVERNOR/inter_staycycles";
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/staycycles_resetfreq";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "95" > "$GOVERNOR/up_threshold";
	echo "OndemandPlus tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# SMARTMAX EPS

if [ $CUR_GOVERNOR = "smartmax_eps" ]; then
	echo "0" > "$GOVERNOR/io_is_busy";
	echo "100" > "$GOVERNOR/max_cpu_load";
	echo "20" > "$GOVERNOR/min_cpu_load";
	echo "20000" > "$GOVERNOR/min_sampling_rate";
	echo "700000" > "$GOVERNOR/ramp_down_step";
	echo "0" > "$GOVERNOR/ramp_up_during_boost";
	echo "0" > "$GOVERNOR/ramp_up_step";
	echo "600000" > "$GOVERNOR/awake_ideal_freq";
	echo "0" > "$GOVERNOR/boost_duration";
	echo "0" > "$GOVERNOR/boost_freq";
	echo "0" > "$GOVERNOR/debug_mask";
	echo "30000" > "$GOVERNOR/down_rate";
	echo "0" > "$GOVERNOR/ignore_nice";
	echo "0" > "$GOVERNOR/input_boost_duration";
	echo "Smartmax_eps tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# INTELLIDEMAND

if [ $CUR_GOVERNOR = "intellidemand" ]; then
	echo "$MIN_CPU_FREQ" > "$GOVERNOR/optimal_freq";
	echo "0" > "$GOVERNOR/powersave_bias";
	echo "1" > "$GOVERNOR/sampling_down_factor";
	echo "2" > "$GOVERNOR/sampling_easy_factor";
	echo "3" > "$GOVERNOR/sampling_interim_factor";
	echo "20000" > "$GOVERNOR/sampling_rate";
	echo "20000" > "$GOVERNOR/sampling_rate_min";
	echo "1100000" > "$GOVERNOR/sync_freq";
	echo "1800000,1800000,1800000,1800000" > "$GOVERNOR/two_phase_freq";
	echo "40000" > "$GOVERNOR/ui_sampling_rate";
	echo "40" > "$GOVERNOR/ui_timeout";
	echo "95" > "$GOVERNOR/up_threshold";
	echo "65" > "$GOVERNOR/up_threshold_any_cpu_load";
	echo "0" > "$GOVERNOR/up_threshold_multi_core";
	echo "Intellidemand tweaks applied. Please ignore any No such files or directory errors, if you encounter one!"
	exit
fi

# TRIPNDROID

if [ $CUR_GOVERNOR = "tripndroid" ]; then
	echo "10000" > "$GOVERNOR/down_sample_time";
	echo "90" > "$GOVERNOR/go_hispeed_load";
	echo "1200000" > "$GOVERNOR/hispeed_freq";
	echo "30000" > "$GOVERNOR/timer_rate";
	echo "50000" > "$GOVERNOR/up_sample_time";
	echo "Tripndroid tweaks applied. Please ignore any "No such files or directory" errors, if you encounter one!"
	exit
fi


# No compatible governor is detected
# Put other governor above this, don't let this be sandwiched by other governor
echo "$CUR_GOVERNOR governor is not supported yet. You can request the support for this governor in the official XDA thread."
