#!/system/bin/sh
# Gov-Tuner init.d tester
# Copyright (C) 2016 Debuffer and Senthil360 @ XDA-Developers
#      With help from Paget96 and Fouad and GreekDragon
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
core="/system/etc/GovTuner"
busybox=/system/etc/GovTuner/busybox
$busybox mount -o remount,rw /system 2>/dev/null
$busybox mount -o remount,rw / 2>/dev/null
echo "Init.d is Working" > /gt_test
$busybox mount -o remount,ro / 2>/dev/null
$busybox mount -o remount,ro /system 2>/dev/null