#!/system/bin/sh
# Gov-Tuner Launcher
# Copyright (C) 2016 Debuffer and Senthil360 @ XDA-Developers
#      With help from Paget96 and F4uzan and GreekDragon
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
core="/system/etc/GovTuner"
busybox=/system/etc/GovTuner/busybox
PROFILE=$($busybox cat /system/etc/GovTuner/current/profile);
$busybox mount -o remount,rw /system 2>/dev/null
$busybox mount -o remount,rw / 2>/dev/null
mount -o remount,rw /system 2>/dev/null
mount -o remount,rw / 2>/dev/null
$busybox sleep 120
sh /system/etc/GovTuner/current/$PROFILE &