#!/system/bin/sh
# Gov-Tuner Battery Profile
# Copyright (C) 2016 Debuffer @ XDA Developers
# 	   With help from Paget96 and F4uzan
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox="/system/etc/GovTuner/busybox"
CUR_GOVERNOR=$($busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);
DIR="/sys/devices/system/cpu/cpufreq"
GOVERNOR="$DIR/$CUR_GOVERNOR"
DIR1="/sys/devices/system/cpu/cpu0/cpufreq"
GOVERNOR1="$DIR1/$CUR_GOVERNOR"
OUTPUT="/data/system/test"
OUTPUT_ID=$($busybox cat /data/system/test)
PROFILE="/system/etc/GovTuner/current/profile"

# Minimum CPU frequency
MIN_CPU_FREQ=$($busybox cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq);

# Maximum CPU frequency
MAX_CPU_FREQ=$($busybox cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq);

echo "Resetting GovTuner"
echo "Applying new profile"
kill -9 $OUTPUT_ID

# GOVERNOR TUNABLES FOR NON-CLUSTER DEVICES

while [ 5 == 5 ]; do
 echo $$ > $OUTPUT
 echo "GovTuner_battery" > $PROFILE
 
 # INTERACTIVE
 
 if [ -d "/sys/devices/system/cpu/cpufreq/$CUR_GOVERNOR" ]; then
 if [ "$CUR_GOVERNOR" = "interactive" ]; then
 for i in /sys/devices/system/cpu/cpufreq/interactive; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "0 800000:50000 1100000:85000 1400000:130000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/max_freq_hysteresis" ]; then
		$busybox echo "0" > "$i/max_freq_hysteresis";
	fi
	if [ -e "$GOVERNOR/align_windows" ]; then
		$busybox echo "0" > "$i/align_windows";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# CONSERVATIVE
 elif [ $CUR_GOVERNOR = "conservative" ]; then
 for i in /sys/devices/system/cpu/cpufreq/conservative; do
	if [ -e "$GOVERNOR/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# YANKACTIVE

 elif [ $CUR_GOVERNOR = "yankactive" ]; then
 for i in /sys/devices/system/cpu/cpufreq/yankactive; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# INTELLIACTIVE

 elif [ $CUR_GOVERNOR = "intelliactive" ]; then
 for i in /sys/devices/system/cpu/cpufreq/intelliactive; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sync_freq" ]; then
		$busybox echo "0" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""


# BIOSHOCK 

 elif [ $CUR_GOVERNOR = "bioshock" ]; then
 for i in /sys/devices/system/cpu/cpufreq/bioshock; do
	if [ -e "$GOVERNOR/down_threshold" ]; then
		$busybox echo "70" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "75000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "85" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""
# LIONFISH 

 elif [ $CUR_GOVERNOR = "lionfish" ]; then
 for i in /sys/devices/system/cpu/cpufreq/lionfish; do
	if [ -e "$GOVERNOR/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/jump_level" ]; then
		$busybox echo "600000" > "$i/jump_level";
	fi
	if [ -e "$GOVERNOR/jump_threshold" ]; then
		$busybox echo "99" > "$i/jump_threshold";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# IMPULSE 

 elif [ $CUR_GOVERNOR = "impulse" ]; then
 for i in /sys/devices/system/cpu/cpufreq/impulse; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/max_freq_hysteresis" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/max_freq_hysteresis";
	fi
	if [ -e "$GOVERNOR/align_windows" ]; then
		$busybox echo "0" > "$i/align_windows";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# UBERDEMAND 

 elif [ $CUR_GOVERNOR = "uberdemand" ]; then
 for i in /sys/devices/system/cpu/cpufreq/uberdemand; do
	if [ -e "$GOVERNOR/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/second_phase_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/second_phase_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# ELECTROACTIVE 

 elif [ $CUR_GOVERNOR = "electroactive" ]; then
 for i in /sys/devices/system/cpu/cpufreq/electroactive; do
	if [ -e "$GOVERNOR/boostfreq" ]; then
		$busybox echo "0" > "$i/boostfreq";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR/freq_responsiveness" ]; then
		$busybox echo "700000" > "$i/freq_responsiveness";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/micro_freq_up_threshold" ]; then
		$busybox echo "99" > "$i/micro_freq_up_threshold";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR/up_threshold_min_freq" ]; then
		$busybox echo "600000" > "$i/up_threshold_min_freq";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# BARRY_ALLEN

 elif [ $CUR_GOVERNOR = "barry_allen" ]; then
 for i in /sys/devices/system/cpu/cpufreq/barry_allen; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/ba_lock" ]; then
		$busybox echo "0" > "$i/ba_lock";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sync_freq" ]; then
		$busybox echo "1100000" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "1500000" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "95" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""
	
	# INTELLIMM
	
	elif [ $CUR_GOVERNOR = "intellimm" ]; then
	for i in /sys/devices/system/cpu/cpufreq/intellimm; do
	if [ -e "$GOVERNOR/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR/down_differential_multi_core" ]; then
		$busybox echo "35" > "$i/down_differential_multi_core";
	fi
	if [ -e "$GOVERNOR/freq_down_step" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_down_step";
	fi
	if [ -e "$GOVERNOR/freq_down_step_barrier" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_down_step_barrier";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/input_event_min_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ" > "$i/input_event_min_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/shortcut" ]; then
		$busybox echo "0" > "$i/shortcut";
	fi
	if [ -e "$GOVERNOR/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "90" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "1500000" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# BLUACTIVE

 elif [ $CUR_GOVERNOR = "bluactive" ]; then
 for i in /sys/devices/system/cpu/cpufreq/bluactive; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "0" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "90000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sync_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "82 $MIN_CPU_FREQ:63 600000:78 700000:57 $MIN_CPU_FREQ:85 900000:89 1100000:93 1200000:91 1300000:86 1400000:72 1500000:67 1700000:91 1$MIN_CPU_FREQ:68 1900000:79" > "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "55000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/two_phase_freq" ]; then
		$busybox echo "1100000,1100000,1100000,1100000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# DANCEDANCE

 elif [ $CUR_GOVERNOR = "dancedance" ]; then
 for i in /sys/devices/system/cpu/cpufreq/dancedance; do
	if [ -e "$GOVERNOR/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# LIONHEART 

 elif [ $CUR_GOVERNOR = "lionheart" ]; then
 for i in /sys/devices/system/cpu/cpufreq/lionheart; do
	if [ -e "$GOVERNOR/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# PEGASUSQ

 elif [ $CUR_GOVERNOR = "pegasusq" ]; then
 for i in /sys/devices/system/cpu/cpufreq/pegasusq; do
	if [ -e "$GOVERNOR/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR/freq_responsiveness" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_responsiveness";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR/up_threshold_min_freq" ]; then
		$busybox echo "600000" > "$i/up_threshold_min_freq";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# ONDEMAND

 elif [ $CUR_GOVERNOR = "ondemand" ]; then
 for i in /sys/devices/system/cpu/cpufreq/ondemand; do
	if [ -e "$GOVERNOR/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/sync_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "90" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# SMARTMAX 

 elif [ $CUR_GOVERNOR = "smartmax" ]; then
 for i in /sys/devices/system/cpu/cpufreq/smartmax; do
	if [ -e "$GOVERNOR/awake_ideal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/awake_ideal_freq";
	fi
	if [ -e "$GOVERNOR/boost_duration" ]; then
		$busybox echo "0" > "$i/boost_duration";
	fi
	if [ -e "$GOVERNOR/boost_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/boost_freq";
	fi
	if [ -e "$GOVERNOR/debug_mask" ]; then
		$busybox echo "32" > "$i/debug_mask";
	fi
	if [ -e "$GOVERNOR/down_rate" ]; then
		$busybox echo "10000" > "$i/down_rate";
	fi
	if [ -e "$GOVERNOR/ignore_nice" ]; then
		$busybox echo "0" > "$i/ignore_nice";
	fi
	if [ -e "$GOVERNOR/input_boost_duration" ]; then
		$busybox echo "0" > "$i/input_boost_duration";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/max_cpu_load" ]; then
		$busybox echo "100" > "$i/max_cpu_load";
	fi
	if [ -e "$GOVERNOR/min_cpu_load" ]; then
		$busybox echo "5" > "$i/min_cpu_load";
	fi
	if [ -e "$GOVERNOR/min_sampling_rate" ]; then
		$busybox echo "20000" > "$i/min_sampling_rate";
	fi
	if [ -e "$GOVERNOR/ramp_down_step" ]; then
		$busybox echo "162000" > "$i/ramp_down_step";
	fi
	if [ -e "$GOVERNOR/ramp_up_during_boost" ]; then
		$busybox echo "0" > "$i/ramp_up_during_boost";
	fi
	if [ -e "$GOVERNOR/ramp_up_step" ]; then
		$busybox echo "100000" > "$i/ramp_up_step";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/suspend_ideal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/suspend_ideal_freq";
	fi
	if [ -e "$GOVERNOR/touch_poke_freq" ]; then
		$busybox echo "0" > "$i/touch_poke_freq";
	fi
	if [ -e "$GOVERNOR/up_rate" ]; then
		$busybox echo "0" > "$i/up_rate";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# OPTIMAX

 elif [ $CUR_GOVERNOR = "optimax" ]; then
 for i in /sys/devices/system/cpu/cpufreq/optimax; do
	if [ -e "$GOVERNOR/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR/optimal_max_freq" ]; then
		$busybox echo "0" > "$i/optimal_max_freq";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/sync_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "90" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# CONSERVATIVEX

 elif [ $CUR_GOVERNOR = "conservativex" ]; then
 for i in /sys/devices/system/cpu/cpufreq/conservativex; do
	if [ -e "$GOVERNOR/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# INTERACTIVE_PRO

 elif [ $CUR_GOVERNOR = "interactive_pro" ]; then
 for i in /sys/devices/system/cpu/cpufreq/interactive_pro; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/freq_calc_thresh" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_calc_thresh";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sync_freq" ]; then
		$busybox echo "700000" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# WHEATLEY

 elif [ $CUR_GOVERNOR = "wheatley" ]; then
 for i in /sys/devices/system/cpu/cpufreq/wheatley; do
	if [ -e "$GOVERNOR/allowed_misses" ]; then
		$busybox echo "5" > "$i/allowed_misses";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/target_residency" ]; then
		$busybox echo "10000" > "$i/target_residency";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# ONDEMAND PLUS

 elif [ $CUR_GOVERNOR = "ondemandplus" ]; then
 for i in /sys/devices/system/cpu/cpufreq/ondemandplus; do
	if [ -e "$GOVERNOR/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR/inter_hifreq" ]; then
		$busybox echo "1100000" > "$i/inter_hifreq";
	fi
	if [ -e "$GOVERNOR/inter_lofreq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/inter_lofreq";
	fi
	if [ -e "$GOVERNOR/inter_staycycles" ]; then
		$busybox echo "2" > "$i/inter_staycycles";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/staycycles_resetfreq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/staycycles_resetfreq";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# SMARTMAX EPS

 elif [ $CUR_GOVERNOR = "smartmax_eps" ]; then
 for i in /sys/devices/system/cpu/cpufreq/smartmax_eps; do
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/max_cpu_load" ]; then
		$busybox echo "100" > "$i/max_cpu_load";
	fi
	if [ -e "$GOVERNOR/min_cpu_load" ]; then
		$busybox echo "20" > "$i/min_cpu_load";
	fi
	if [ -e "$GOVERNOR/min_sampling_rate" ]; then
		$busybox echo "20000" > "$i/min_sampling_rate";
	fi
	if [ -e "$GOVERNOR/ramp_down_step" ]; then
		$busybox echo "700000" > "$i/ramp_down_step";
	fi
	if [ -e "$GOVERNOR/ramp_up_during_boost" ]; then
		$busybox echo "0" > "$i/ramp_up_during_boost";
	fi
	if [ -e "$GOVERNOR/ramp_up_step" ]; then
		$busybox echo "0" > "$i/ramp_up_step";
	fi
	if [ -e "$GOVERNOR/awake_ideal_freq" ]; then
		$busybox echo "600000" > "$i/awake_ideal_freq";
	fi
	if [ -e "$GOVERNOR/boost_duration" ]; then
		$busybox echo "0" > "$i/boost_duration";
	fi
	if [ -e "$GOVERNOR/boost_freq" ]; then
		$busybox echo "0" > "$i/boost_freq";
	fi
	if [ -e "$GOVERNOR/debug_mask" ]; then
		$busybox echo "0" > "$i/debug_mask";
	fi
	if [ -e "$GOVERNOR/down_rate" ]; then
		$busybox echo "30000" > "$i/down_rate";
	fi
	if [ -e "$GOVERNOR/ignore_nice" ]; then
		$busybox echo "1" > "$i/ignore_nice";
	fi
	if [ -e "$GOVERNOR/"input_boost_duration ]; then
		$busybox echo "0" > "$i/input_boost_duration";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# INTELLIDEMAND

 elif [ $CUR_GOVERNOR = "intellidemand" ]; then
 for i in /sys/devices/system/cpu/cpufreq/intellidemand; do
	if [ -e "$GOVERNOR/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_easy_factor" ]; then
		$busybox echo "2" > "$i/sampling_easy_factor";
	fi
	if [ -e "$GOVERNOR/sampling_interim_factor" ]; then
		$busybox echo "3" > "$i/sampling_interim_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/sync_freq" ]; then
		$busybox echo "1100000" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR/ui_sampling_rate" ]; then
		$busybox echo "40000" > "$i/ui_sampling_rate";
	fi
	if [ -e "$GOVERNOR/ui_timeout" ]; then
		$busybox echo "40" > "$i/ui_timeout";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "75" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# TRIPNDROID

 elif [ $CUR_GOVERNOR = "tripndroid" ]; then
 for i in /sys/devices/system/cpu/cpufreq/tripndroid; do
	if [ -e "$GOVERNOR/down_sample_time" ]; then
		$busybox echo "10000" > "$i/down_sample_time";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/up_sample_time" ]; then
		$busybox echo "50000" > "$i/up_sample_time";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# ELEMENTALX

 elif [ $CUR_GOVERNOR = "elementalx" ]; then
 for i in /sys/devices/system/cpu/cpufreq/elementalx; do
	if [ -e "$GOVERNOR/active_floor_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/active_floor_freq";
	fi
	if [ -e "$GOVERNOR/down_differential" ]; then
		$busybox echo "15" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR/powersave" ]; then
		$busybox echo "1" > "$i/powersave";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# BLU_ACTIVE

 elif [ $CUR_GOVERNOR = "blu_active" ]; then
 for i in /sys/devices/system/cpu/cpufreq/blu_active; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/fastlane" ]; then
		$busybox echo "0" > "$i/fastlane";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/input_boost_freq" ]; then
		$busybox echo "600000" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/low_load_down_threshold" ]; then
		$busybox echo "37" > "$i/low_load_down_threshold";
	fi
	if [ -e "$GOVERNOR/max_freq_hysteresis" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/max_freq_hysteresis";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/two_phase_freq" ]; then
		$busybox echo "1100000,1100000,1100000,1100000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""
	
# ZZMOOVE
	
 elif [ $CUR_GOVERNOR = "zzmoove" ]; then
 for i in /sys/devices/system/cpu/cpufreq/zzmoove; do
	if [ -e "$GOVERNOR/afs_treshold1" ]; then
		$busybox echo "40" > "$i/afs_treshold1";
	fi
	if [ -e "$GOVERNOR/afs_treshold2" ]; then
		$busybox echo "53" > "$i/afs_treshold2";
	fi
	if [ -e "$GOVERNOR/afs_treshold3" ]; then
		$busybox echo "72" > "$i/afs_treshold3";
	fi
	if [ -e "$GOVERNOR/afs_treshold4" ]; then
		$busybox echo "91" > "$i/afs_treshold4";
	fi
	if [ -e "$GOVERNOR/auto_adjust_freq_threshold" ]; then
		$busybox echo "0" > "$i/auto_adjust_freq_threshold";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug1" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug1";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug2" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug2";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug3" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug3";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug4" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug4";
	fi
	if [ -e "$GOVERNOR/disable_hotplug" ]; then
		$busybox echo "1" > "$i/disable_hotplug";
	fi
	if [ -e "$GOVERNOR/disable_hotplug_sleep" ]; then
		$busybox echo "1" > "$i/disable_hotplug_sleep";
	fi
	if [ -e "$GOVERNOR/early_demand" ]; then
		$busybox echo "0" > "$i/early_demand";
	fi
	if [ -e "$GOVERNOR/early_demand_sleep" ]; then
		$busybox echo "1" > "$i/early_demand_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_down" ]; then
		$busybox echo "6" > "$i/fast_scaling_down";
	fi
	if [ -e "$GOVERNOR/fast_scaling_down_sleep" ]; then
		$busybox echo "8" > "$i/fast_scaling_down_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_up_sleep" ]; then
		$busybox echo "0" > "$i/fast_scaling_up_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_up" ]; then
		$busybox echo "0" > "$i/fast_scaling_up";
	fi
	if [ -e "$GOVERNOR/freq_limit" ]; then
		$busybox echo "0" > "$i/freq_limit";
	fi
	if [ -e "$GOVERNOR/freq_limit_sleep" ]; then
		$busybox echo "900000" > "$i/freq_limit_sleep";
	fi
	if [ -e "$GOVERNOR/grad_up_threshold" ]; then
		$busybox echo "30" > "$i/grad_up_threshold";
	fi
	if [ -e "$GOVERNOR/grad_up_threshold_sleep" ]; then
		$busybox echo "38" > "$i/grad_up_threshold_sleep";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/inputboost_cycles" ]; then
		$busybox echo "0" > "$i/inputboost_cycles";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_cycles" ]; then
		$busybox echo "0" > "$i/inputboost_punch_cycles";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_freq" ]; then
		$busybox echo "0" > "$i/inputboost_punch_freq";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_epenmove" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_epenmove";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_fingerdown" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_fingerdown";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_fingermove" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_fingermove";
	fi
	if [ -e "$GOVERNOR/inputboost_typingbooster_cores" ]; then
		$busybox echo "0" > "$i/inputboost_typingbooster_cores";
	fi
	if [ -e "$GOVERNOR/inputboost_typingbooster_up_threshold" ]; then
		$busybox echo "60" > "$i/inputboost_typingbooster_up_threshold";
	fi
	if [ -e "$GOVERNOR/inputboost_up_threshold" ]; then
		$busybox echo "100" > "$i/inputboost_up_threshold";
	fi
	if [ -e "$GOVERNOR/music_max_freq" ]; then
		$busybox echo "600000" > "$i/music_max_freq";
	fi
	if [ -e "$GOVERNOR/music_min_cores" ]; then
		$busybox echo "0" > "$i/music_min_cores";
	fi
	if [ -e "$GOVERNOR/music_min_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/music_min_freq";
	fi
	if [ -e "$GOVERNOR/profile_number" ]; then
		$busybox echo "0" > "$i/profile_number";
	fi
	if [ -e "$GOVERNOR/profile_sticky_mode" ]; then
		$busybox echo "1" > "$i/profile_sticky_mode";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_down_max_momentum" ]; then
		$busybox echo "0" > "$i/sampling_down_max_momentum"; 
	fi
	if [ -e "$GOVERNOR/sampling_down_max_sensitivity" ]; then
		$busybox echo "75" > "$i/sampling_down_max_sensitivity"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_current" ]; then
		$busybox echo "250000" > "$i/sampling_rate_current"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle" ]; then
		$busybox echo "100000" > "$i/sampling_rate_idle"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle_delay" ]; then
		$busybox echo "0" > "$i/sampling_rate_idle_delay"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle_threshold" ]; then
		$busybox echo "50" > "$i/sampling_rate_idle_threshold"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_sleep_multiplier" ]; then
		$busybox echo "2" > "$i/sampling_rate_sleep_multiplier"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_cycles" ]; then
		$busybox echo "4" > "$i/scaling_block_cycles"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_force_down" ]; then
		$busybox echo "2" > "$i/scaling_block_force_down"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_freq" ]; then
		$busybox echo "900000" > "$i/scaling_block_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_threshold" ]; then
		$busybox echo "0" > "$i/scaling_block_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_down_threshold" ]; then
		$busybox echo "95" > "$i/scaling_fastdown_down_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_freq" ]; then
		$busybox echo "0" > "$i/scaling_fastdown_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_up_threshold" ]; then
		$busybox echo "99" > "$i/scaling_fastdown_up_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_proportional" ]; then
		$busybox echo "0" > "$i/scaling_proportional"; 
	fi
	if [ -e "$GOVERNOR/scaling_responsiveness_freq" ]; then
		$busybox echo "0" > "$i/scaling_responsiveness_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_responsiveness_up_threshold" ]; then
		$busybox echo "90" > "$i/scaling_responsiveness_up_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_up_block_cycles" ]; then
		$busybox echo "0" > "$i/scaling_up_block_cycles"; 
	fi
	if [ -e "$GOVERNOR/scaling_up_block_freq" ]; then
		$busybox echo "0" > "$i/scaling_up_block_freq"; 
	fi
	if [ -e "$GOVERNOR/smooth_up" ]; then
		$busybox echo "75" > "$i/smooth_up"; 
	fi
	if [ -e "$GOVERNOR/smooth_up_sleep" ]; then
		$busybox echo "100" > "$i/smooth_up_sleep"; 
	fi
done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""
 else 
 echo "$CUR_GOVERNOR governor is not compatible. Please, change it to a compatible governor."
 echo "        You can know the compatible governors checking the XDA thread."
 echo ""
 fi
 sleep 180

# GOVERNOR TUNABLES FOR DUAL-CLUSTER DEVICES

# INTERACTIVE
 elif [ -d "/sys/devices/system/cpu/cpu0/cpufreq/$CUR_GOVERNOR" ]; then
 if [ "$CUR_GOVERNOR" = "interactive" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/interactive; do
	if [ -e "$GOVERNOR1/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR1/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR1/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR1/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/max_freq_hysteresis" ]; then
		$busybox echo "0" > "$i/max_freq_hysteresis";
	fi
	if [ -e "$GOVERNOR1/align_windows" ]; then
		$busybox echo "0" > "$i/align_windows";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# CONSERVATIVE
 elif [ $CUR_GOVERNOR = "conservative" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/conservative; do
	if [ -e "$GOVERNOR1/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR1/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# YANKACTIVE

 elif [ $CUR_GOVERNOR = "yankactive" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/yankactive; do
	if [ -e "$GOVERNOR1/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR1/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR1/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR1/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# INTELLIACTIVE

 elif [ $CUR_GOVERNOR = "intelliactive" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/intelliactive; do
	if [ -e "$GOVERNOR1/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR1/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR1/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR1/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sync_freq" ]; then
		$busybox echo "0" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR1/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR1/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""


# BIOSHOCK 

 elif [ $CUR_GOVERNOR = "bioshock" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/bioshock; do
	if [ -e "$GOVERNOR1/down_threshold" ]; then
		$busybox echo "70" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR1/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "75000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "85" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""
# LIONFISH 

 elif [ $CUR_GOVERNOR = "lionfish" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/lionfish; do
	if [ -e "$GOVERNOR1/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR1/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/jump_level" ]; then
		$busybox echo "600000" > "$i/jump_level";
	fi
	if [ -e "$GOVERNOR1/jump_threshold" ]; then
		$busybox echo "99" > "$i/jump_threshold";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# IMPULSE 

 elif [ $CUR_GOVERNOR = "impulse" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/impulse; do
	if [ -e "$GOVERNOR1/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR1/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR1/max_freq_hysteresis" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/max_freq_hysteresis";
	fi
	if [ -e "$GOVERNOR1/align_windows" ]; then
		$busybox echo "0" > "$i/align_windows";
	fi
	if [ -e "$GOVERNOR1/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# UBERDEMAND 

 elif [ $CUR_GOVERNOR = "uberdemand" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/uberdemand; do
	if [ -e "$GOVERNOR1/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/second_phase_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/second_phase_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# ELECTROACTIVE 

 elif [ $CUR_GOVERNOR = "electroactive" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/electroactive; do
	if [ -e "$GOVERNOR1/boostfreq" ]; then
		$busybox echo "0" > "$i/boostfreq";
	fi
	if [ -e "$GOVERNOR1/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR1/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR1/freq_responsiveness" ]; then
		$busybox echo "700000" > "$i/freq_responsiveness";
	fi
	if [ -e "$GOVERNOR1/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/micro_freq_up_threshold" ]; then
		$busybox echo "99" > "$i/micro_freq_up_threshold";
	fi
	if [ -e "$GOVERNOR1/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR1/up_threshold_min_freq" ]; then
		$busybox echo "600000" > "$i/up_threshold_min_freq";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""
	
# INTELLIMM
elif [ $CUR_GOVERNOR = "intellimm" ]; then
for i in /sys/devices/system/cpu/*/cpufreq/intellimm; do
	if [ -e "$GOVERNOR1/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR1/down_differential_multi_core" ]; then
		$busybox echo "35" > "$i/down_differential_multi_core";
	fi
	if [ -e "$GOVERNOR1/freq_down_step" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_down_step";
	fi
	if [ -e "$GOVERNOR1/freq_down_step_barrier" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_down_step_barrier";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/input_event_min_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ" > "$i/input_event_min_freq";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR1/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/shortcut" ]; then
		$busybox echo "0" > "$i/shortcut";
	fi
	if [ -e "$GOVERNOR1/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "90" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_freq" ]; then
		$busybox echo "1500000" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# BARRY_ALLEN

 elif [ $CUR_GOVERNOR = "barry_allen" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/barry_allen; do
	if [ -e "$GOVERNOR1/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR1/ba_lock" ]; then
		$busybox echo "0" > "$i/ba_lock";
	fi
	if [ -e "$GOVERNOR1/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR1/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR1/boostpulse_duration" ]; then
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sync_freq" ]; then
		$busybox echo "1100000" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR1/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR1/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_freq" ]; then
		$busybox echo "1500000" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "95" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# BLUACTIVE

 elif [ $CUR_GOVERNOR = "bluactive" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/bluactive; do
	if [ -e "$GOVERNOR1/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR1/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR1/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR1/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sync_freq" ]; then
		$busybox echo "0" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR1/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR1/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# DANCEDANCE

 elif [ $CUR_GOVERNOR = "dancedance" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/dancedance; do
	if [ -e "$GOVERNOR1/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR1/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# LIONHEART 

 elif [ $CUR_GOVERNOR = "lionheart" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/lionheart; do
	if [ -e "$GOVERNOR1/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR1/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# PEGASUSQ

 elif [ $CUR_GOVERNOR = "pegasusq" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/pegasusq; do
	if [ -e "$GOVERNOR1/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR1/freq_responsiveness" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_responsiveness";
	fi
	if [ -e "$GOVERNOR1/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR1/up_threshold_min_freq" ]; then
		$busybox echo "600000" > "$i/up_threshold_min_freq";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# ONDEMAND

 elif [ $CUR_GOVERNOR = "ondemand" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/ondemand; do
	if [ -e "$GOVERNOR1/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR1/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/sync_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "90" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR1/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# SMARTMAX 

 elif [ $CUR_GOVERNOR = "smartmax" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/smartmax; do
	if [ -e "$GOVERNOR1/awake_ideal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/awake_ideal_freq";
	fi
	if [ -e "$GOVERNOR1/boost_duration" ]; then
		$busybox echo "0" > "$i/boost_duration";
	fi
	if [ -e "$GOVERNOR1/boost_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/boost_freq";
	fi
	if [ -e "$GOVERNOR1/debug_mask" ]; then
		$busybox echo "32" > "$i/debug_mask";
	fi
	if [ -e "$GOVERNOR1/down_rate" ]; then
		$busybox echo "10000" > "$i/down_rate";
	fi
	if [ -e "$GOVERNOR1/ignore_nice" ]; then
		$busybox echo "0" > "$i/ignore_nice";
	fi
	if [ -e "$GOVERNOR1/input_boost_duration" ]; then
		$busybox echo "0" > "$i/input_boost_duration";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/max_cpu_load" ]; then
		$busybox echo "100" > "$i/max_cpu_load";
	fi
	if [ -e "$GOVERNOR1/min_cpu_load" ]; then
		$busybox echo "5" > "$i/min_cpu_load";
	fi
	if [ -e "$GOVERNOR1/min_sampling_rate" ]; then
		$busybox echo "20000" > "$i/min_sampling_rate";
	fi
	if [ -e "$GOVERNOR1/ramp_down_step" ]; then
		$busybox echo "162000" > "$i/ramp_down_step";
	fi
	if [ -e "$GOVERNOR1/ramp_up_during_boost" ]; then
		$busybox echo "0" > "$i/ramp_up_during_boost";
	fi
	if [ -e "$GOVERNOR1/ramp_up_step" ]; then
		$busybox echo "100000" > "$i/ramp_up_step";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/suspend_ideal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/suspend_ideal_freq";
	fi
	if [ -e "$GOVERNOR1/touch_poke_freq" ]; then
		$busybox echo "0" > "$i/touch_poke_freq";
	fi
	if [ -e "$GOVERNOR1/up_rate" ]; then
		$busybox echo "0" > "$i/up_rate";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# OPTIMAX

 elif [ $CUR_GOVERNOR = "optimax" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/optimax; do
	if [ -e "$GOVERNOR1/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR1/optimal_max_freq" ]; then
		$busybox echo "0" > "$i/optimal_max_freq";
	fi
	if [ -e "$GOVERNOR1/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/sync_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "90" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR1/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# CONSERVATIVEX

 elif [ $CUR_GOVERNOR = "conservativex" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/conservativex; do
	if [ -e "$GOVERNOR1/down_threshold" ]; then
		$busybox echo "95" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR1/freq_step" ]; then
		$busybox echo "7" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# INTERACTIVE_PRO

 elif [ $CUR_GOVERNOR = "interactive_pro" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/interactive_pro; do
	if [ -e "$GOVERNOR1/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR1/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR1/boostpulse_duration" ]; then
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR1/freq_calc_thresh" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_calc_thresh";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sync_freq" ]; then
		$busybox echo "700000" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR1/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# WHEATLEY

 elif [ $CUR_GOVERNOR = "wheatley" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/wheatley; do
	if [ -e "$GOVERNOR1/allowed_misses" ]; then
		$busybox echo "5" > "$i/allowed_misses";
	fi
	if [ -e "$GOVERNOR1/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/target_residency" ]; then
		$busybox echo "10000" > "$i/target_residency";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# ONDEMAND PLUS

 elif [ $CUR_GOVERNOR = "ondemandplus" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/ondemandplus; do
	if [ -e "$GOVERNOR1/down_differential" ]; then
		$busybox echo "35" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR1/inter_hifreq" ]; then
		$busybox echo "1100000" > "$i/inter_hifreq";
	fi
	if [ -e "$GOVERNOR1/inter_lofreq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/inter_lofreq";
	fi
	if [ -e "$GOVERNOR1/inter_staycycles" ]; then
		$busybox echo "2" > "$i/inter_staycycles";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/staycycles_resetfreq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/staycycles_resetfreq";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# SMARTMAX EPS

 elif [ $CUR_GOVERNOR = "smartmax_eps" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/smartmax_eps; do
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/max_cpu_load" ]; then
		$busybox echo "100" > "$i/max_cpu_load";
	fi
	if [ -e "$GOVERNOR1/min_cpu_load" ]; then
		$busybox echo "20" > "$i/min_cpu_load";
	fi
	if [ -e "$GOVERNOR1/min_sampling_rate" ]; then
		$busybox echo "20000" > "$i/min_sampling_rate";
	fi
	if [ -e "$GOVERNOR1/ramp_down_step" ]; then
		$busybox echo "700000" > "$i/ramp_down_step";
	fi
	if [ -e "$GOVERNOR1/ramp_up_during_boost" ]; then
		$busybox echo "0" > "$i/ramp_up_during_boost";
	fi
	if [ -e "$GOVERNOR1/ramp_up_step" ]; then
		$busybox echo "0" > "$i/ramp_up_step";
	fi
	if [ -e "$GOVERNOR1/awake_ideal_freq" ]; then
		$busybox echo "600000" > "$i/awake_ideal_freq";
	fi
	if [ -e "$GOVERNOR1/boost_duration" ]; then
		$busybox echo "0" > "$i/boost_duration";
	fi
	if [ -e "$GOVERNOR1/boost_freq" ]; then
		$busybox echo "0" > "$i/boost_freq";
	fi
	if [ -e "$GOVERNOR1/debug_mask" ]; then
		$busybox echo "0" > "$i/debug_mask";
	fi
	if [ -e "$GOVERNOR1/down_rate" ]; then
		$busybox echo "30000" > "$i/down_rate";
	fi
	if [ -e "$GOVERNOR1/ignore_nice" ]; then
		$busybox echo "1" > "$i/ignore_nice";
	fi
	if [ -e "$GOVERNOR1/"input_boost_duration ]; then
		$busybox echo "0" > "$i/input_boost_duration";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# INTELLIDEMAND

 elif [ $CUR_GOVERNOR = "intellidemand" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/intellidemand; do
	if [ -e "$GOVERNOR1/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR1/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_easy_factor" ]; then
		$busybox echo "2" > "$i/sampling_easy_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_interim_factor" ]; then
		$busybox echo "3" > "$i/sampling_interim_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/sync_freq" ]; then
		$busybox echo "1100000" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR1/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR1/ui_sampling_rate" ]; then
		$busybox echo "40000" > "$i/ui_sampling_rate";
	fi
	if [ -e "$GOVERNOR1/ui_timeout" ]; then
		$busybox echo "40" > "$i/ui_timeout";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "95" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "75" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR1/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# TRIPNDROID

 elif [ $CUR_GOVERNOR = "tripndroid" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/tripndroid; do
	if [ -e "$GOVERNOR1/down_sample_time" ]; then
		$busybox echo "10000" > "$i/down_sample_time";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/up_sample_time" ]; then
		$busybox echo "50000" > "$i/up_sample_time";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# ELEMENTALX

 elif [ $CUR_GOVERNOR = "elementalx" ]; then
 for i in sys/devices/system/cpu/*/cpufreq/elementalx sys/devices/system/cpu/cpufreq/elementalx; do
	if [ -e "$GOVERNOR1/active_floor_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/active_floor_freq";
	fi
	if [ -e "$GOVERNOR1/down_differential" ]; then
		$busybox echo "15" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR1/powersave" ]; then
		$busybox echo "1" > "$i/powersave";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate";
	fi
	if [ -e "$GOVERNOR1/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min";
	fi
	if [ -e "$GOVERNOR1/up_threshold" ]; then
		$busybox echo "99" > "$i/up_threshold";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""

# BLU_ACTIVE

 elif [ $CUR_GOVERNOR = "blu_active" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/blu_active; do
	if [ -e "$GOVERNOR1/above_hispeed_delay" ]; then
		$busybox echo "0 1100000:50000 1400000:150000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR1/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR1/fastlane" ]; then
		$busybox echo "0" > "$i/fastlane";
	fi
	if [ -e "$GOVERNOR1/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR1/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/input_boost_freq" ]; then
		$busybox echo "600000" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR1/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR1/low_load_down_threshold" ]; then
		$busybox echo "37" > "$i/low_load_down_threshold";
	fi
	if [ -e "$GOVERNOR1/max_freq_hysteresis" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/max_freq_hysteresis";
	fi
	if [ -e "$GOVERNOR1/min_sample_time" ]; then
		$busybox echo "35000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR1/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR1/target_loads" ]; then
		$busybox echo "98 $MIN_CPU_FREQ:81 400000:42 600000:66 800000:83 1100000:94 1400000:99"> "$i/target_loads";
	fi
	if [ -e "$GOVERNOR1/timer_rate" ]; then
		$busybox echo "28000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR1/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR1/two_phase_freq" ]; then
		$busybox echo "1100000,1100000,1100000,1100000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR1/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
 done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""
	
# ZZMOOVE
	
 elif [ $CUR_GOVERNOR = "zzmoove" ]; then
 for i in /sys/devices/system/cpu/*/cpufreq/zzmoove; do
	if [ -e "$GOVERNOR/afs_treshold1" ]; then
		$busybox echo "40" > "$i/afs_treshold1";
	fi
	if [ -e "$GOVERNOR/afs_treshold2" ]; then
		$busybox echo "53" > "$i/afs_treshold2";
	fi
	if [ -e "$GOVERNOR/afs_treshold3" ]; then
		$busybox echo "72" > "$i/afs_treshold3";
	fi
	if [ -e "$GOVERNOR/afs_treshold4" ]; then
		$busybox echo "91" > "$i/afs_treshold4";
	fi
	if [ -e "$GOVERNOR/auto_adjust_freq_threshold" ]; then
		$busybox echo "0" > "$i/auto_adjust_freq_threshold";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug1" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug1";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug2" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug2";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug3" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug3";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug4" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug4";
	fi
	if [ -e "$GOVERNOR/disable_hotplug" ]; then
		$busybox echo "1" > "$i/disable_hotplug";
	fi
	if [ -e "$GOVERNOR/disable_hotplug_sleep" ]; then
		$busybox echo "1" > "$i/disable_hotplug_sleep";
	fi
	if [ -e "$GOVERNOR/early_demand" ]; then
		$busybox echo "0" > "$i/early_demand";
	fi
	if [ -e "$GOVERNOR/early_demand_sleep" ]; then
		$busybox echo "1" > "$i/early_demand_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_down" ]; then
		$busybox echo "6" > "$i/fast_scaling_down";
	fi
	if [ -e "$GOVERNOR/fast_scaling_down_sleep" ]; then
		$busybox echo "8" > "$i/fast_scaling_down_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_up_sleep" ]; then
		$busybox echo "0" > "$i/fast_scaling_up_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_up" ]; then
		$busybox echo "0" > "$i/fast_scaling_up";
	fi
	if [ -e "$GOVERNOR/freq_limit" ]; then
		$busybox echo "0" > "$i/freq_limit";
	fi
	if [ -e "$GOVERNOR/freq_limit_sleep" ]; then
		$busybox echo "900000" > "$i/freq_limit_sleep";
	fi
	if [ -e "$GOVERNOR/grad_up_threshold" ]; then
		$busybox echo "30" > "$i/grad_up_threshold";
	fi
	if [ -e "$GOVERNOR/grad_up_threshold_sleep" ]; then
		$busybox echo "38" > "$i/grad_up_threshold_sleep";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/inputboost_cycles" ]; then
		$busybox echo "0" > "$i/inputboost_cycles";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_cycles" ]; then
		$busybox echo "0" > "$i/inputboost_punch_cycles";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_freq" ]; then
		$busybox echo "0" > "$i/inputboost_punch_freq";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_epenmove" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_epenmove";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_fingerdown" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_fingerdown";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_fingermove" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_fingermove";
	fi
	if [ -e "$GOVERNOR/inputboost_typingbooster_cores" ]; then
		$busybox echo "0" > "$i/inputboost_typingbooster_cores";
	fi
	if [ -e "$GOVERNOR/inputboost_typingbooster_up_threshold" ]; then
		$busybox echo "60" > "$i/inputboost_typingbooster_up_threshold";
	fi
	if [ -e "$GOVERNOR/inputboost_up_threshold" ]; then
		$busybox echo "100" > "$i/inputboost_up_threshold";
	fi
	if [ -e "$GOVERNOR/music_max_freq" ]; then
		$busybox echo "600000" > "$i/music_max_freq";
	fi
	if [ -e "$GOVERNOR/music_min_cores" ]; then
		$busybox echo "0" > "$i/music_min_cores";
	fi
	if [ -e "$GOVERNOR/music_min_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/music_min_freq";
	fi
	if [ -e "$GOVERNOR/profile_number" ]; then
		$busybox echo "0" > "$i/profile_number";
	fi
	if [ -e "$GOVERNOR/profile_sticky_mode" ]; then
		$busybox echo "1" > "$i/profile_sticky_mode";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_down_max_momentum" ]; then
		$busybox echo "0" > "$i/sampling_down_max_momentum"; 
	fi
	if [ -e "$GOVERNOR/sampling_down_max_sensitivity" ]; then
		$busybox echo "75" > "$i/sampling_down_max_sensitivity"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_current" ]; then
		$busybox echo "250000" > "$i/sampling_rate_current"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle" ]; then
		$busybox echo "100000" > "$i/sampling_rate_idle"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle_delay" ]; then
		$busybox echo "0" > "$i/sampling_rate_idle_delay"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle_threshold" ]; then
		$busybox echo "50" > "$i/sampling_rate_idle_threshold"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_min" ]; then
		$busybox echo "30000" > "$i/sampling_rate_min"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_sleep_multiplier" ]; then
		$busybox echo "2" > "$i/sampling_rate_sleep_multiplier"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_cycles" ]; then
		$busybox echo "4" > "$i/scaling_block_cycles"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_force_down" ]; then
		$busybox echo "2" > "$i/scaling_block_force_down"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_freq" ]; then
		$busybox echo "900000" > "$i/scaling_block_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_threshold" ]; then
		$busybox echo "0" > "$i/scaling_block_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_down_threshold" ]; then
		$busybox echo "95" > "$i/scaling_fastdown_down_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_freq" ]; then
		$busybox echo "0" > "$i/scaling_fastdown_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_up_threshold" ]; then
		$busybox echo "99" > "$i/scaling_fastdown_up_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_proportional" ]; then
		$busybox echo "0" > "$i/scaling_proportional"; 
	fi
	if [ -e "$GOVERNOR/scaling_responsiveness_freq" ]; then
		$busybox echo "0" > "$i/scaling_responsiveness_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_responsiveness_up_threshold" ]; then
		$busybox echo "90" > "$i/scaling_responsiveness_up_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_up_block_cycles" ]; then
		$busybox echo "0" > "$i/scaling_up_block_cycles"; 
	fi
	if [ -e "$GOVERNOR/scaling_up_block_freq" ]; then
		$busybox echo "0" > "$i/scaling_up_block_freq"; 
	fi
	if [ -e "$GOVERNOR/smooth_up" ]; then
		$busybox echo "75" > "$i/smooth_up"; 
	fi
	if [ -e "$GOVERNOR/smooth_up_sleep" ]; then
		$busybox echo "100" > "$i/smooth_up_sleep"; 
	fi
done
	$busybox echo "Battery $CUR_GOVERNOR tweaks applied."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
$busybox echo "PROFILE SUCESSFULLY APPLIED. CLOSE THIS WINDOW TAB OR THIS MESSAGE WILL KEEP HERE FOREVER."
	echo ""
 else 
 echo "$CUR_GOVERNOR governor is not compatible. Please, change it to a compatible governor."
 echo "        You can know the compatible governors checking the XDA thread."
 echo ""
 fi
 sleep 180
 else
 $busybox sleep 180
 sh "/system/etc/GovTuner/profiles/GovTuner_balanced"
 fi
done