#!/system/bin/sh
# Gov-Tuner Performance Profile
# Copyright (C) 2016 Debuffer &  Senthil360 @ XDA Developers
# 	   With help from Paget96 and F4uzan and GreekDragon
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

# TODO: Fix this on Cluster-based SoC

busybox="/system/etc/GovTuner/busybox"
CUR_GOVERNOR=$($busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);
PROFILE="/system/etc/GovTuner/current/profile"
FIRST_RUN="/data/system/first_run"
CHECK1=$($busybox cat /data/system/first_run);
REG_DIR="/sys/devices/system/cpu/cpufreq"
CLU_DIR="/sys/devices/system/cpu/cpu0/cpufreq"
HCHECK=/etc/GovTuner/zzmoove/HCheck
CH=$($busybox cat $HCHECK);
HON=/etc/GovTuner/zzmoove/HON
HOFF=/etc/GovTuner/zzmoove/HOFF

# Minimum CPU frequency
MIN_CPU_FREQ=$($busybox cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq);

$busybox mount -o remount,rw /system 2>/dev/null
mount -o remount,rw /system 2>/dev/null

if [ "$CHECK1" -eq "1" ]; then
   echo "First Run"
   echo ""
else
   OUTPUT_ID=$($busybox cat /data/system/test)
   echo "Resetting GovTuner"
   echo ""
   echo "Applying new profile"
   echo ""
   echo 0 > $FIRST_RUN
   kill -9 $OUTPUT_ID
fi

while [ 5 == 5 ]; do
$busybox mount -o remount,rw /system 2>/dev/null
mount -o remount,rw /system 2>/dev/null
 OUTPUT="/data/system/test"
 echo $$ > $OUTPUT
 echo "GovTuner_performance" > $PROFILE
 
if [ $CUR_GOVERNOR == "zzmoove" ]; then
if [ $CH == 0 ]; then
sh $HON
elif [ $CH == 1 ]; then
sh $HOFF
fi
fi

#For REGULAR and SMALL clusters
 if [ -d "/sys/devices/system/cpu/cpufreq/$CUR_GOVERNOR" ]; then
     FINAL_PATH=$REG_DIR
 elif [ -d "/sys/devices/system/cpu/cpu0/cpufreq/$CUR_GOVERNOR" ]; then
     FINAL_PATH=$CLU_DIR
 else
     echo "Unsupported device architecture"
 fi
 GOVERNOR="$FINAL_PATH/$CUR_GOVERNOR"

 #TUNING_BEGINS
 
 if [ -d "$GOVERNOR" ]; then
 for i in $FINAL_PATH/$CUR_GOVERNOR; do
	if [ -e "$GOVERNOR/above_hispeed_delay" ]; then
		$busybox echo "20000" > "$i/above_hispeed_delay";
	fi
	if [ -e "$GOVERNOR/boost" ]; then
		$busybox echo "0" > "$i/boost";
	fi
	if [ -e "$GOVERNOR/boostpulse" ]; then
		$busybox echo "0" > "$i/boostpulse";
	fi
	if [ -e "$GOVERNOR/boostpulse_duration" ]; then	
		$busybox echo "0" > "$i/boostpulse_duration";
	fi
	if [ -e "$GOVERNOR/go_hispeed_load" ]; then
		$busybox echo "300" > "$i/go_hispeed_load";
	fi
	if [ -e "$GOVERNOR/hispeed_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/max_freq_hysteresis" ]; then
		$busybox echo "0" > "$i/max_freq_hysteresis";
	fi
	if [ -e "$GOVERNOR/align_windows" ]; then
		$busybox echo "0" > "$i/align_windows";
	fi
	if [ -e "$GOVERNOR/io_is_busy" ]; then
		$busybox echo "1" > "$i/io_is_busy";
	fi
	if [ -e "$GOVERNOR/min_sample_time" ]; then
		$busybox echo "50000" > "$i/min_sample_time";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/target_loads" ]; then
		$busybox echo "0 $MIN_CPU_FREQ:40 400000:20 600000:30 700000:35 800000:40 900000:45 1100000:55 1400000:60 1700000:75 1900000:95" > "$i/target_loads";
	fi
	if [ -e "$GOVERNOR/timer_rate" ]; then
		$busybox echo "20000" > "$i/timer_rate";
	fi
	if [ -e "$GOVERNOR/timer_slack" ]; then
		$busybox echo "-1" > "$i/timer_slack";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_freq" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_freq";
	fi
	if [ -e "$GOVERNOR/up_threshold_any_cpu_load" ]; then
		$busybox echo "0" > "$i/up_threshold_any_cpu_load";
	fi
	if [ -e "$GOVERNOR/down_threshold" ]; then
		$busybox echo "40" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR/freq_step" ]; then
		$busybox echo "30" > "$i/freq_step";
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "53" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR/sync_freq" ]; then
		$busybox echo "0" > "$i/sync_freq";
	fi
	if [ -e "$GOVERNOR/two_phase_freq" ]; then
		$busybox echo "960000,960000,960000,960000" > "$i/two_phase_freq";
	fi
	if [ -e "$GOVERNOR/jump_level" ]; then
		$busybox echo "1000000" > "$i/jump_level";
	fi
	if [ -e "$GOVERNOR/jump_threshold" ]; then
		$busybox echo "60" > "$i/jump_threshold";
	fi
	if [ -e "$GOVERNOR/powersave_bias" ]; then
		$busybox echo "0" > "$i/powersave_bias";
	fi
	if [ -e "$GOVERNOR/down_differential" ]; then
		$busybox echo "8" > "$i/down_differential";
	fi
	if [ -e "$GOVERNOR/second_phase_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/second_phase_freq";
	fi
	if [ -e "$GOVERNOR/boostfreq" ]; then
		$busybox echo "0" > "$i/boostfreq";
	fi
	if [ -e "$GOVERNOR/micro_freq_up_threshold" ]; then
		$busybox echo "65" > "$i/micro_freq_up_threshold";
	fi
	if [ -e "$GOVERNOR/up_threshold_min_freq" ]; then
		$busybox echo "600000" > "$i/up_threshold_min_freq";
	fi
	if [ -e "$GOVERNOR/ba_lock" ]; then
		$busybox echo "0" > "$i/ba_lock";
	fi
	if [ -e "$GOVERNOR/down_differential_multi_core" ]; then
		$busybox echo "35" > "$i/down_differential_multi_core";
	fi
	if [ -e "$GOVERNOR/freq_down_step" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_down_step";
	fi
	if [ -e "$GOVERNOR/freq_down_step_barrier" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_down_step_barrier";
	fi
	if [ -e "$GOVERNOR/input_event_min_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ, $MIN_CPU_FREQ" > "$i/input_event_min_freq";
	fi
	if [ -e "$GOVERNOR/optimal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/optimal_freq";
	fi
	if [ -e "$GOVERNOR/shortcut" ]; then
		$busybox echo "0" > "$i/shortcut";
	fi
	if [ -e "$GOVERNOR/up_threshold_multi_core" ]; then
		$busybox echo "0" > "$i/up_threshold_multi_core";
	fi
	if [ -e "$GOVERNOR/freq_responsiveness" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/freq_responsiveness";
	fi
	if [ -e "$GOVERNOR/awake_ideal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/awake_ideal_freq";
	fi
	if [ -e "$GOVERNOR/boost_duration" ]; then
		$busybox echo "0" > "$i/boost_duration";
	fi
	if [ -e "$GOVERNOR/boost_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/boost_freq";
	fi
	if [ -e "$GOVERNOR/debug_mask" ]; then
		$busybox echo "32" > "$i/debug_mask";
	fi
	if [ -e "$GOVERNOR/down_rate" ]; then
		$busybox echo "10000" > "$i/down_rate";
	fi
	if [ -e "$GOVERNOR/ignore_nice" ]; then
		$busybox echo "0" > "$i/ignore_nice";
	fi
	if [ -e "$GOVERNOR/input_boost_duration" ]; then
		$busybox echo "0" > "$i/input_boost_duration";
	fi
	if [ -e "$GOVERNOR/max_cpu_load" ]; then
		$busybox echo "100" > "$i/max_cpu_load";
	fi
	if [ -e "$GOVERNOR/min_cpu_load" ]; then
		$busybox echo "5" > "$i/min_cpu_load";
	fi
	if [ -e "$GOVERNOR/min_sampling_rate" ]; then
		$busybox echo "20000" > "$i/min_sampling_rate";
	fi
	if [ -e "$GOVERNOR/ramp_down_step" ]; then
		$busybox echo "162000" > "$i/ramp_down_step";
	fi
	if [ -e "$GOVERNOR/ramp_up_during_boost" ]; then
		$busybox echo "0" > "$i/ramp_up_during_boost";
	fi
	if [ -e "$GOVERNOR/ramp_up_step" ]; then
		$busybox echo "100000" > "$i/ramp_up_step";
	fi
	if [ -e "$GOVERNOR/suspend_ideal_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/suspend_ideal_freq";
	fi
	if [ -e "$GOVERNOR/touch_poke_freq" ]; then
		$busybox echo "0" > "$i/touch_poke_freq";
	fi
	if [ -e "$GOVERNOR/up_rate" ]; then
		$busybox echo "0" > "$i/up_rate";
	fi
	if [ -e "$GOVERNOR/optimal_max_freq" ]; then
		$busybox echo "2000000" > "$i/optimal_max_freq";
	fi
	if [ -e "$GOVERNOR/freq_calc_thresh" ]; then
		$busybox echo "1100000" > "$i/freq_calc_thresh";
	fi
	if [ -e "$GOVERNOR/allowed_misses" ]; then
		$busybox echo "5" > "$i/allowed_misses";
	fi
	if [ -e "$GOVERNOR/target_residency" ]; then
		$busybox echo "10000" > "$i/target_residency";
	fi
	if [ -e "$GOVERNOR/inter_hifreq" ]; then
		$busybox echo "1500000" > "$i/inter_hifreq";
	fi
	if [ -e "$GOVERNOR/inter_lofreq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/inter_lofreq";
	fi
	if [ -e "$GOVERNOR/inter_staycycles" ]; then
		$busybox echo "4" > "$i/inter_staycycles";
	fi
	if [ -e "$GOVERNOR/staycycles_resetfreq" ]; then
		$busybox echo "1100000" > "$i/staycycles_resetfreq";
	fi
	if [ -e "$GOVERNOR/input_boost_duration" ]; then
		$busybox echo "0" > "$i/input_boost_duration";
	fi
	if [ -e "$GOVERNOR/sampling_easy_factor" ]; then
		$busybox echo "2" > "$i/sampling_easy_factor";
	fi
	if [ -e "$GOVERNOR/sampling_interim_factor" ]; then
		$busybox echo "3" > "$i/sampling_interim_factor";
	fi
	if [ -e "$GOVERNOR/ui_sampling_rate" ]; then
		$busybox echo "45000" > "$i/ui_sampling_rate";
	fi
	if [ -e "$GOVERNOR/ui_timeout" ]; then
		$busybox echo "40" > "$i/ui_timeout";
	fi
	if [ -e "$GOVERNOR/down_sample_time" ]; then
		$busybox echo "10000" > "$i/down_sample_time";
	fi
	if [ -e "$GOVERNOR/up_sample_time" ]; then
		$busybox echo "50000" > "$i/up_sample_time";
	fi
	if [ -e "$GOVERNOR/active_floor_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/active_floor_freq";
	fi
	if [ -e "$GOVERNOR/powersave" ]; then
		$busybox echo "0" > "$i/powersave";
	fi
	if [ -e "$GOVERNOR/fastlane" ]; then
		$busybox echo "0" > "$i/fastlane";
	fi
	if [ -e "$GOVERNOR/input_boost_freq" ]; then
		$busybox echo "600000" > "$i/hispeed_freq";
	fi
	if [ -e "$GOVERNOR/low_load_down_threshold" ]; then
		$busybox echo "10" > "$i/low_load_down_threshold";
	fi

if [ $CUR_GOVERNOR = "zzmoove" ]; then

	pn=$($busybox cat $GOVERNOR/profile_number)
	if [ $pn != 0 ]; then
		$busybox echo "0" > "$i/profile_number";
	fi
	if [ -e "$GOVERNOR/afs_threshold1" ]; then
		$busybox echo "15" > "$i/afs_threshold1";
	fi
	if [ -e "$GOVERNOR/afs_threshold2" ]; then
		$busybox echo "25" > "$i/afs_threshold2";
	fi
	if [ -e "$GOVERNOR/afs_threshold3" ]; then
		$busybox echo "40" > "$i/afs_threshold3";
	fi
	if [ -e "$GOVERNOR/afs_threshold4" ]; then
		$busybox echo "70" > "$i/afs_threshold4";
	fi
	if [ -e "$GOVERNOR/auto_adjust_freq_threshold" ]; then
		$busybox echo "0" > "$i/auto_adjust_freq_threshold";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug1" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug1";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug2" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug2";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug3" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug3";
	fi
	if [ -e "$GOVERNOR/block_down_multiplier_hotplug4" ]; then
		$busybox echo "1" > "$i/block_down_multiplier_hotplug4";
	fi
	if [ -e "$GOVERNOR/down_threshold" ]; then
		$busybox echo "30" > "$i/down_threshold";
	fi
	if [ -e "$GOVERNOR/down_threshold_hotplug1" ]; then
		$busybox echo "20" > "$i/down_threshold_hotplug1";
	fi
	if [ -e "$GOVERNOR/down_threshold_hotplug2" ]; then
		$busybox echo "35" > "$i/down_threshold_hotplug2";
	fi
	if [ -e "$GOVERNOR/down_threshold_hotplug3" ]; then
		$busybox echo "45" > "$i/down_threshold_hotplug3";
	fi
	if [ -e "$GOVERNOR/down_threshold_sleep" ]; then
		$busybox echo "65" > "$i/down_threshold_sleep";
	fi
	if [ -e "$GOVERNOR/early_demand" ]; then
		$busybox echo "0" > "$i/early_demand";
	fi
	if [ -e "$GOVERNOR/early_demand_sleep" ]; then
		$busybox echo "0" > "$i/early_demand_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_down" ]; then
		$busybox echo "2" > "$i/fast_scaling_down";
	fi
	if [ -e "$GOVERNOR/fast_scaling_down_sleep" ]; then
		$busybox echo "6" > "$i/fast_scaling_down_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_up_sleep" ]; then
		$busybox echo "0" > "$i/fast_scaling_up_sleep";
	fi
	if [ -e "$GOVERNOR/fast_scaling_up" ]; then
		$busybox echo "2" > "$i/fast_scaling_up";
	fi
	if [ -e "$GOVERNOR/freq_limit" ]; then
		$busybox echo "0" > "$i/freq_limit";
	fi
	if [ -e "$GOVERNOR/freq_limit_sleep" ]; then
		$busybox echo "900000" > "$i/freq_limit_sleep";
	fi
	if [ -e "$GOVERNOR/grad_up_threshold" ]; then
		$busybox echo "35" > "$i/grad_up_threshold";
	fi
	if [ -e "$GOVERNOR/grad_up_threshold_sleep" ]; then
		$busybox echo "80" > "$i/grad_up_threshold_sleep";
	fi
	if [ -e "$GOVERNOR/hotplug_block_down_cycles" ]; then
		$busybox echo "0" > "$i/hotplug_block_down_cycles"
	fi
	if [ -e "$GOVERNOR/hotplug__block_up_cycles" ]; then
		$busybox echo "0" > "$i/hotplug_block_up_cycles"
	fi
	if [ -e "$GOVERNOR/hotplug_engage_freq" ]; then
		$busybox echo "0" > "$i/hotplug_engage_freq"
	fi
	if [ -e "$GOVERNOR/hotplug_idle_freq" ]; then
		$busybox echo "0" > "$i/hotplug_idle_freq"
	fi
	if [ -e "$GOVERNOR/hotplug_idle_threshold" ]; then
		$busybox echo "0" > "$i/hotplug_idle_threshold"
	fi
	if [ -e "$GOVERNOR/hotplug_lock" ]; then
		$busybox echo "0" > "$i/hotplug_lock"
	fi
	if [ -e "$GOVERNOR/hotplug_max_limit" ]; then
		$busybox echo "0" > "$i/hotplug_max_limit"
	fi
	if [ -e "$GOVERNOR/hotplug_min_limit" ]; then
		$busybox echo "0" > "$i/hotplug_min_limit"
	fi
	if [ -e "$GOVERNOR/hotplug_sleep" ]; then
		$busybox echo "0" > "$i/hotplug_sleep"
	fi
	if [ -e "$GOVERNOR/hotplug_stagger_down" ]; then
		$busybox echo "0" > "$i/hotplug_stagger_down"
	fi
	if [ -e "$GOVERNOR/hotplug_stagger_up" ]; then
		$busybox echo "0" > "$i/hotplug_stagger_up"
	fi
	if [ -e "$GOVERNOR/ignore_nice_load" ]; then
		$busybox echo "1" > "$i/ignore_nice_load";
	fi
	if [ -e "$GOVERNOR/inputboost_cycles" ]; then
		$busybox echo "0" > "$i/inputboost_cycles";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_cycles" ]; then
		$busybox echo "0" > "$i/inputboost_punch_cycles";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_freq" ]; then
		$busybox echo "0" > "$i/inputboost_punch_freq";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_epenmove" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_epenmove";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_fingerdown" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_fingerdown";
	fi
	if [ -e "$GOVERNOR/inputboost_punch_on_fingermove" ]; then
		$busybox echo "0" > "$i/inputboost_punch_on_fingermove";
	fi
	if [ -e "$GOVERNOR/inputboost_typingbooster_cores" ]; then
		$busybox echo "0" > "$i/inputboost_typingbooster_cores";
	fi
	if [ -e "$GOVERNOR/inputboost_typingbooster_up_threshold" ]; then
		$busybox echo "60" > "$i/inputboost_typingbooster_up_threshold";
	fi
	if [ -e "$GOVERNOR/inputboost_up_threshold" ]; then
		$busybox echo "100" > "$i/inputboost_up_threshold";
	fi
	if [ -e "$GOVERNOR/music_max_freq" ]; then
		$busybox echo "600000" > "$i/music_max_freq";
	fi
	if [ -e "$GOVERNOR/music_min_cores" ]; then
		$busybox echo "0" > "$i/music_min_cores";
	fi
	if [ -e "$GOVERNOR/music_min_freq" ]; then
		$busybox echo "$MIN_CPU_FREQ" > "$i/music_min_freq";
	fi
	if [ -e "$GOVERNOR/sampling_down_factor" ]; then
		$busybox echo "1" > "$i/sampling_down_factor";
	fi
	if [ -e "$GOVERNOR/sampling_down_max_momentum" ]; then
		$busybox echo "0" > "$i/sampling_down_max_momentum"; 
	fi
	if [ -e "$GOVERNOR/sampling_down_max_sensitivity" ]; then
		$busybox echo "75" > "$i/sampling_down_max_sensitivity"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate" ]; then
		$busybox echo "100000" > "$i/sampling_rate"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle" ]; then
		$busybox echo "100000" > "$i/sampling_rate_idle"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle_delay" ]; then
		$busybox echo "0" > "$i/sampling_rate_idle_delay"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_idle_threshold" ]; then
		$busybox echo "50" > "$i/sampling_rate_idle_threshold"; 
	fi
	if [ -e "$GOVERNOR/sampling_rate_sleep_multiplier" ]; then
		$busybox echo "2" > "$i/sampling_rate_sleep_multiplier"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_cycles" ]; then
		$busybox echo "0" > "$i/scaling_block_cycles"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_force_down" ]; then
		$busybox echo "0" > "$i/scaling_block_force_down"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_freq" ]; then
		$busybox echo "0" > "$i/scaling_block_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_block_threshold" ]; then
		$busybox echo "0" > "$i/scaling_block_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_down_threshold" ]; then
		$busybox echo "0" > "$i/scaling_fastdown_down_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_freq" ]; then
		$busybox echo "0" > "$i/scaling_fastdown_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_fastdown_up_threshold" ]; then
		$busybox echo "0" > "$i/scaling_fastdown_up_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_proportional" ]; then
		$busybox echo "0" > "$i/scaling_proportional"; 
	fi
	if [ -e "$GOVERNOR/scaling_responsiveness_freq" ]; then
		$busybox echo "0" > "$i/scaling_responsiveness_freq"; 
	fi
	if [ -e "$GOVERNOR/scaling_responsiveness_up_threshold" ]; then
		$busybox echo "0" > "$i/scaling_responsiveness_up_threshold"; 
	fi
	if [ -e "$GOVERNOR/scaling_up_block_cycles" ]; then
		$busybox echo "0" > "$i/scaling_up_block_cycles"; 
	fi
	if [ -e "$GOVERNOR/scaling_up_block_freq" ]; then
		$busybox echo "0" > "$i/scaling_up_block_freq"; 
	fi
	if [ -e "$GOVERNOR/smooth_up" ]; then
		$busybox echo "75" > "$i/smooth_up"; 
	fi
	if [ -e "$GOVERNOR/smooth_up_sleep" ]; then
		$busybox echo "100" > "$i/smooth_up_sleep"; 
	fi
	if [ -e "$GOVERNOR/up_threshold" ]; then
		$busybox echo "40" > "$i/up_threshold";
	fi
	if [ -e "$GOVERNOR/up_threshold_hotplug1" ]; then
		$busybox echo "25" > "$i/up_threshold_hotplug1";
	fi
	if [ -e "$GOVERNOR/up_threshold_hotplug2" ]; then
		$busybox echo "40" > "$i/up_threshold_hotplug2";
	fi
	if [ -e "$GOVERNOR/up_threshold_hotplug3" ]; then
		$busybox echo "70" > "$i/up_threshold_hotplug3";
	fi
	if [ -e "$GOVERNOR/up_threshold_hotplug_freq1" ]; then
		$busybox echo "0" > "$i/up_threshold_hotplug_freq1";
	fi
	if [ -e "$GOVERNOR/up_threshold_hotplug_freq2" ]; then
		$busybox echo "0" > "$i/up_threshold_hotplug_freq2";
	fi
	if [ -e "$GOVERNOR/up_threshold_hotplug_freq3" ]; then
		$busybox echo "0" > "$i/up_threshold_hotplug_freq3";
	fi
	if [ -e "$GOVERNOR/up_threshold_sleep" ]; then
		$busybox echo "90" > "$i/up_threshold_sleep";
	fi
fi
 done
 sleep 180 
 fi
done
